### ISSUE TITLE
blank server browser

### ISSUE THREAD

**Issue by 10ked** [aclist/dztui#100]
i had to reinstall python3.12 (i picked this as the latest stable version) and after i had to install pip on
it to allow pygobject to be installed i ended up with a blank unpopulated server browser. This was the output
on a console when i ran dzgui:
dzgui.sh
Initializing setup...
All OK. Kicking off UI...
/home/dave/.local/share/dzgui/helpers/ui.py:1472: Warning: ../gobject/gsignal.c:2693: handler '147' of instance '0x221e3d0' is not blocked
  widget.handler_unblock_by_func(func)

I do not know if this is relevant to the problem but maybe it's a start. The version of dzgui.sh is 5.0.2 
![dzgui](https://github.com/aclist/dztui/assets/9946347/a6850294-ddac-44bf-9ab6-c98a4ffa218a)

**Comment by 10ked** [comment]
ok here it is. Hope this helps.
[DZGUI_DEBUG.log](https://github.com/aclist/dztui/files/14219390/DZGUI_DEBUG.log)

**Comment by aclist** [comment]
I have issued an update (5.0.3) that should fix this. If it does not, please attach the results of the following script:

```
#!/usr/bin/env bash
source $HOME/.config/dztui/dztuirc
limit=20000                                                                               
url="https://api.steampowered.com/IGameServersService/GetServerList/v1/?filter=\appid\221100&limit=$limit&key=$steam_api"
curl -Ls "$url" | jq -r '.response.servers|length'
```

**Comment by 10ked** [comment]
ok i tried the 5.0.3 and the same problem occurred and i am assuming the debug log was what you wanted
with the changes to dzgui.sh you said i should add if the 5.0.3 update did not work so i have attached the debug
log again so maybe we can figure out why this is happening. 
[DZGUI_DEBUG.log](https://github.com/aclist/dztui/files/14225525/DZGUI_DEBUG.log)

**Comment by aclist** [comment]
I want to see the results of the script I pasted in https://github.com/aclist/dztui/issues/100#issuecomment-1935728152

You have to save that to a file, make it executable, run it, and paste the output. It seems like the Steam API is not returning the server list for you. Are you sure your Steam API key is set correctly? (Check the file `/home/dave/.config/dztui/dztuirc`)

**Comment by 10ked** [comment]
Um yeah it was the steam api key. Well actually the key was right but there was a single space in the quotations ""
in front of the steam api key that was interfering with things which was my bad. Sorry about this, but i think "whitespace" may have interfered with things. It might be an idea to have a warning that steam api key is not right or valid in a case like this. Anyways it looks like the problem has been solved for now.

**Comment by aclist** [comment]
> Um yeah it was the steam api key. Well actually the key was right but there was a single space in the quotations ""
in front of the steam api key that was interfering with things which was my bad. Sorry about this, but i think "whitespace" may have interfered with things. It might be an idea to have a warning that steam api key is not right or valid in a case like this. Anyways it looks like the problem has been solved for now.

When performing first-time setup, the API keys are validated, and if the server returns an error, the user is prompted to insert the right API key again. It should not be possible to insert an invalid API key in the configuration file since it is repeatedly tested before allowing the user to run the app. However, I'll give another audit to see where this might be occurring. Are you sure you did not modify your config file at any time?
