### ISSUE TITLE
Launcher Stuck in Debug mode

### ISSUE THREAD

**Issue by ElijahHW** [aclist/dztui#107]
Hiya, just did a fresh installation of this and each time I try to join a server, be it modded or official, it keeps giving me the "dry-run" message. I have not purposely set it in debug mode, and have also tried to configure the script to say `debug=0`. However, it keeps giving the same dry-run message each time. Would greatly appreciate a pointer here.

![image](https://github.com/aclist/dztui/assets/53635291/d11747a5-538a-4e0d-a348-1df871477b3c)
![image](https://github.com/aclist/dztui/assets/53635291/a048c7b0-34bb-4a4c-9077-6c5e08f9b1ed)

**Comment by ElijahHW** [comment]
![image](https://github.com/aclist/dztui/assets/53635291/7cb36c20-d929-49f7-b94a-199feb8eb7a1)

**Comment by ElijahHW** [comment]
I updated to release branch a few times, and that seems to have resolved the issue, its no longer in debug mode.

**Comment by aclist** [comment]
Thank you for the report; I will look into this. It has been reported at least once on a separate channel, so it does seem to indicate a bug somewhere in the way this value is being set. Is this on Steam Deck?

**Comment by aclist** [comment]
Was the `Debug Mode` button depressed immediately on the right panel when you opened the server browser?

**Comment by ElijahHW** [comment]
@aclist This was on PC, using latest version of BazziteOS, so immutable, if that's relevant. I did dont recall pressing the debug button, nor did I see it until you mentioned it now... I was only knocking about in the settings.

**Comment by aclist** [comment]
Due to a design flaw (which I will change after this report), the config file expects a state of empty for the `debug` key rather than a value of `0`. Clicking this button to the off state (not depressed) empties the debug key in the config file, rather than flipping it to zero.

As for why this would be enabled by default, I did a cursory review of the code and didn't see anything that jumped out at me yet, unless you had an old config file from your $HOME that was picked up. Had you installed the application before? You did say this was a fresh install, but did you have your $HOME on a separate partition?

**Comment by ElijahHW** [comment]
My $HOME is on my main partition. I might have tried to download this (DZGUI) once before on the same system and not properly removed it last time or something, so the old config file might have stayed. So what you mention is possible, but cannot 100% confirm it either.

**Comment by aclist** [comment]
Config files sticking around is considered best practice, because removing the application should not obliterate the user's long-lived preferences. It does sound like the old config got inherited, and you were going in circles because you were trying to manually alter the config file instead of using the button. 

But I'll look into hardening this logic a bit here and seeing if there is anything I missed. I don't think debug should ever start enabled by default on its own, unless a prior config file was present. The debug setting does persist reboots of the application, so once you decide to turn the button on, it will stay depressed next session, unless you explicitly click it off.

I don't think there's anything more you need to test here. Thanks for the report. I will keep the ticket open until concluding my tests.

If you encounter any other issues, please let me know. (Via a new ticket)

**Comment by ElijahHW** [comment]
Got a few additional questions regarding the project, may I message you elsewhere?

**Comment by aclist** [comment]
> Got a few additional questions regarding the project, may I message you elsewhere?

Is this issue of a private or sensitive nature (e.g. job offers, legal matters, security vulnerabilities)?

I try to do transparent development and communicate with users in the open here, so that if other users have similar questions in the future, they will find the answers to their questions.

If this relates to a suggestion/advice/idea/offer to help/etc., there is a dedicated discussion forum here: https://github.com/aclist/dztui/discussions. You are free to post any questions that would be considered off-topic for a bug ticket in that area.

If the question is in fact private, I will make a private communication channel for you.
