### ISSUE TITLE
DZGUI does not fetch any servers.

### ISSUE THREAD

**Issue by GKourp** [aclist/dztui#113]
DGZUI does not fetch any servers and when trying to add them to join by ip it times out.

Playing on steam deck with DZGUI 5.2.3.

**Comment by aclist** [comment]
I can't reproduce either of these scenarios on a Steam Deck test bench using the latest version. It sounds like a transitory network error or a malformed API key. If you are encountering problems and continually trying to reconnect, bear in mind that you are repeatedly querying Steam's master server, which may force a cooldown (rate limiting) if you are doing it too much.

After launching DZGUI and encountering this problem, you'll have to attach the log file generated at `$HOME/deck/.local/state/dzgui/logs/DZGUI_DEBUG.log`.

**Comment by GKourp** [comment]
I had a hunch it might be the network I am on, will try a different network and see if that solves it. Will update once performed.

**Comment by aclist** [comment]
I am sorry for the slow response: I saw your first message, but it looks like you edited your second response into the original message, so I did not receive a subsequent notification from GitHub. In the future, you can just add replies directly below the thread so that notifications get sent out.

I will take a look at your logs a bit later and see what comes up.

**Comment by aclist** [comment]
This doesn't look like a current log file. It says that your DZGUI version is `3.3.13`, and it doesn't show any connection info. Was this an old log you found in the DZGUI directory itself? Check the path again and make sure that you run DZGUI once, then quit, then pull the log from `$HOME/deck/.local/state/dzgui/logs/DZGUI_DEBUG.log.`

**Comment by GKourp** [comment]
I did have an issue where I needed to log back into my account, I can't remember the specifics at this time but I did have to disable and enable steam guard again if I remember correctly.

**Comment by aclist** [comment]
Is everything working for you at this time?

In the next release, I will be adding some more error dialogs that trigger in the event of no servers being fetched and warn the user about what steps to take.

**Comment by GKourp** [comment]
Still does not work, nothing happens after it attempts to fetch the servers.

**Comment by aclist** [comment]
If you don't mind, can you try regenerating your API key? It sounds like your old one may be defunct.

You can also try running the build on the testing branch (`Options > Toggle release branch`), which adds the aforementioned warnings and cooldowns if the server list comes back empty.

**Comment by aclist** [comment]
Can you clarify if this is on Wi-Fi or wired?

**Comment by GKourp** [comment]
I only have tried on Wi-Fi, I only play on Wi-Fi.

**Comment by GKourp** [comment]
How can I regerate my API key and apply it?

**Comment by aclist** [comment]
> I only have tried on Wi-Fi, I only play on Wi-Fi.

DayZ exhibits some issues associated with Wi-Fi, but the problem is non-specific and I don't think it's the cause of the issue here.

> How can I regerate my API key and apply it?

- Navigate here: https://steamcommunity.com/dev/apikey
- Choose Revoke My Steam Web API key
- Follow the steps here: https://aclist.github.io/dzgui/dzgui.html#_api_key_server_ids
- In DZGUI, go to Options > Change Steam API key

**Comment by GKourp** [comment]
Server list now loads, thanks a bunch for your help and patience.

**Comment by aclist** [comment]
I'm sorry you had difficulties. Feel free to open another ticket if this issue occurs again.
