### ISSUE TITLE
Im on arch and dzgui cant find my dayz file

### ISSUE THREAD

**Issue by TobyJ-B** [aclist/dztui#117]
i focus it too /home/toby/.steam/steam but it isnt biting any clues?

**Comment by aclist** [comment]
1. Default Steam location is on Arch `/home/toby/.local/share/Steam`
2. Do you have games installed on multiple drives? If DayZ is on a different partition or drive and you added that as a "library folder" in Steam, you'll have to specify that location:

Open Steam -> Settings -> Storage -> Select libraries from the dropdown to see which one DayZ is installed to

**Comment by TobyJ-B** [comment]
It seems too have fixed itself today for some reason. Files were all in the right place.

**Comment by aclist** [comment]
Most likely explanation: if you recently moved around the location of DayZ to another drive, it sometimes takes Steam some time to synchronize this change internally. Usually the best approach would be to make sure Steam has been fully restarted after migration any files, so that the locations Steam reports to DZGUI are up to date. But I understand that restarting Steam may be unexpected behavior, so I'll work on documenting this in more detail. A non-trivial number of users have run into similar problems when changing around the location of their games.
