### ISSUE TITLE
No connection could be established to the remote server (github.com).

### ISSUE THREAD

**Issue by LArtDesChOiX** [aclist/dztui#158]
Heeeeeey

The launcher dont work for me today.

No connection could be established to the remote server (github.com).

Please help.. Work great yesterday.

**Comment by LArtDesChOiX** [comment]
Anyone have an help please ??

**Comment by aclist** [comment]
It sounds like you might be spamming input and trying to reopen the application repeatedly in a short span of time, putting you on a cooldown. Wait some time and try again.

If the issue persists, check your network settings. Have you changed something about your network recently?

**Comment by LArtDesChOiX** [comment]
No i change nothin, thank for your answer..
Same today, dont wok, very strange

**Comment by aclist** [comment]
A few tests:

1. Does this site report if you are using ipv6? https://test-ipv6.com/
2. From a terminal, does the command `ping -4 github.com` work?
3. From a terminal, does the command `ping -6 github.com` work?

**Comment by LArtDesChOiX** [comment]
No IPv6 address detected [more info]
<https://test-ipv6.com/faq_no_ipv6.html>

Ping 4 and 6 look dont work :/

**Comment by aclist** [comment]
The problem is localized to your network then. Since you can connect to GitHub by a browser but can't ping it, It sounds like your DNS is not configured to resolve correctly. Restart your network, flush your DNS cache, make sure you are using a reliable public DNS server (Cloudflare, Google) if the one provided by your ISP is not good, and restart systemd-resolved. Check your resolved.conf (located in different places depending on Linux distribution) to see what DNS server you might be using.

If you are behind a complex network firewall, contact your network administrator.

You didn't specify which distribution you are using, but you should be able to find numerous guides online explaining how to resolve DNS issues.

**Comment by LArtDesChOiX** [comment]
# Generated by NetworkManager
nameserver 192.168.0.1
nameserver 8.8.8.8
nameserver 172.XX.10.1

I dont understand

**Comment by aclist** [comment]
> I dont understand, i change nothin.. Work 2 Days ago.

The last change to DZGUI was on 2024-10-05, over a week ago. Nothing involving the networking above was changed. The problem is localized to your network. 

As for why that changed, sometimes DNS records may update automatically when you reconnect to your network or when you restart your machine.

The file `/etc/resolv.conf` can be written automatically to by multiple processes and is not meant to be edited manually. It looks like NetworkManager added DNS records there for you. The fact that the loopback address is listed at the top seems like it might cause some problems, but I am not sure.

The standard solution to DNS management on modern systems is to use systemd-resolved and specify the DNS server in the file `/etc/systemd/resolved.conf`. If your system does not use systemd-resolved, you can also use resolvconf (`man resolvconf`), which helps manage the `resolv.conf` file without manual intervention. resolvconf is itself configured through the file `/etc/resolvconf.conf` (notice the different spelling).

As a control, I think you could try specifying only a public DNS server and removing references to the local machine/loopback. (Obviously, back up conf files before trying that.)

As a last resort, check your hosts file to see if github is blacklisted there for some reason.

This issue is not being caused by DZGUI and is out of the scope of troubleshooting we can provide. The above are some ideas/suggestions, but we cannot provide network troubleshooting help here. You can try searching for "can't ping github", and you will find results like this: https://bbs.archlinux.org/viewtopic.php?id=267331

Hopefully this points you in the right direction. Many small things could have changed in your system, network, or ISP, so it's not something we can diagnose here.

**Comment by LArtDesChOiX** [comment]
many thanks for your help bro.. I continu to try

**Comment by LArtDesChOiX** [comment]
Hoooow.... When i use a box internet. Like a box in home, it's look work...
Butbi have only a 4g connect, with my Phone 😅
And this one dont work... Strange
