### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mkuehn94** [aclist/dztui#19]
**Info**
DZGUI version:0.7.1
Mode (normal/debug):debug
Server ID:12927278
Linux distribution:Arch Linux x86_64 Kernel: 5.18.14-arch1-1            

**Bug description**
when I launch the script it says:
---
[INFO] Checking for new version
[INFO] Polling servers. Please wait.
---
Then the last message goes away and it spawns a process called column that takes a lot of cpu power
the command is : "column -t -s	 -o │  "
after a lot of time it just crashes

**To Reproduce**
run script under my distro

**Expected behavior**
the client to open

**Comment by mkuehn94** [comment]
using newer version fixed issue

**Comment by aclist** [comment]
Hi, just saw this issue that you self-closed. You reported this as a bug with `DZGUI`, but it looks like you were using `DZTUI 0.7.1`. There is no new version of DZTUI. Did you switch to DZGUI? If this bug is still present in DZTUI, I want to fix it. 

There were no changes between `0.7.0` and `0.7.1` that would affect the `column`command. Can you reproduce this?
