### ISSUE TITLE
Fails to load mods if the mod name contains a space

### ISSUE THREAD

**Issue by scandalouss** [aclist/dztui#2]
Title. Depending on the mods, either the game will start and either never finish loading as not all mods were loaded, or it will crash before ever opening. 

The script produces this output when joining:

`Selection: 7
[INFO] Mod check passed
[INFO] Connecting to: [V++] Deathmatch 3PP | Custom Gamemode | DayZVPP.com 51.222.191.212:2302
/home/david/.local/share/Steam/steam.sh: line 124: VERSION_ID: unbound variable
/home/david/.local/share/Steam/steam.sh: line 574: no match: Scopes;@[VPP]DeathMatch;@[VPP]DeathMatchWeapons;@BuilderItems;@MoreGuns_Test;@CF;"
/home/david/.local/share/Steam/steam.sh: line 124: VERSION_ID: unbound variable
steam.sh[15269]: Running Steam on gentoo  64-bit
steam.sh[15269]: STEAM_RUNTIME is enabled by the user
setup.sh[15439]: Steam runtime environment up-to-date!
steam.sh[15269]: Steam client's requirements are satisfied
Good luck out there. DZTUI 0.1.0
`

It fails to load every mod past the last space in the list of mods. I've attempted to fix it myself but I'm not familiar enough with bash and couldn't get it to correctly load every mod.

**Comment by aclist** [comment]
Thanks for the note.  The Steam launch options are properly encapsulated: the `-mods` will be enclosed in quotation marks as: `"-mods=@somemod;@someothermod;`". I believe spaces are being handled correctly here on the launch side of things, and the symlinks are being treated correctly, too, so far as I can see. There does seem to be some word splitting problem with your trace, though.

I want to clarify a few things: when you say the game starts but doesn't finish loading, are you saying that it:
- Launches the client
- Shows the V++ server splash screen graphics
-  Red loading bar starts loading mods, but freezes partway through?

Or are you saying that:
- Steam attempts to launch the game client with some terminal output, then fails altogether?

I tested connecting to servers with mods containing a space, and to the server above, and it worked. 

Would you mind setting the `debug` flag to 1 on line 19 of the script and attempting to connect as usual, then pasting the debug output it gives you here? This prints a dry run of the launch options that would have been used.

As a test, try copying this dry run output verbatim and using it to launch the game directly via the terminal and see if the result differs.

Also, could you paste the exact directory path where the mods are installed? Is it under your default Steam path?

And could you indicate the distro and shell you used? I assume gentoo and Bourne shell.

**Comment by scandalouss** [comment]
I'm running gentoo and my shell is bash, my mods are installed in the default path, ~/.steam/steam/steamapps/workshop/content/221100

To clarify, the former is correct, although it changes from server to server. In my example above, I'm able to make it to the V++ splash screen and it loads to a little above 50% then hangs indefinitely. However some servers don't make it to the loading screen and crash with some strange generic game related error about missing assets, depending on how many mods the server is running and how many didn't get loaded.

Here is my debug output:

`[DEBUG] steam -applaunch 221100  -connect=51.222.191.212:2302 "-mod=@Better-Snap-Sounds;@Inventory Move Sounds;@Advanced Weapon Scopes;@[VPP]DeathMatch;@[VPP]DeathMatchWeapons;@BuilderItems;@MoreGuns_Test;@CF;"`

Running this command directly from the terminal produces the same output as before:

`david@x570pc ~/Documents/Source/dztui $ steam -applaunch 221100  -connect=51.222.191.212:2302 "-mod=@Better-Snap-Sounds;@Inventory Move Sounds;@Advanced Weapon Scopes;@[VPP]DeathMatch;@[VPP]DeathMatchWeapons;@BuilderItems;@MoreGuns_Test;@CF;"
/home/david/.local/share/Steam/steam.sh: line 124: VERSION_ID: unbound variable
/home/david/.local/share/Steam/steam.sh: line 574: no match: Scopes;@[VPP]DeathMatch;@[VPP]DeathMatchWeapons;@BuilderItems;@MoreGuns_Test;@CF;
/home/david/.local/share/Steam/steam.sh: line 124: VERSION_ID: unbound variable
steam.sh[20969]: Running Steam on gentoo  64-bit
steam.sh[20969]: STEAM_RUNTIME is enabled by the user
setup.sh[21100]: Steam runtime environment up-to-date!
steam.sh[20969]: Steam client's requirements are satisfied
`

I can get it to directly launch from steam by pasting the -connect and -mod line into the launch options, but in order to connect successfully I had to move the double quote in the -mod line, from

`"-mod=@Better-Snap-Sounds;@Inventory Move Sounds;@Advanced Weapon Scopes;@[VPP]DeathMatch;@[VPP]DeathMatchWeapons;@BuilderItems;@MoreGuns_Test;@CF;"`

To

`-mod="@Better-Snap-Sounds;@Inventory Move Sounds;@Advanced Weapon Scopes;@[VPP]DeathMatch;@[VPP]DeathMatchWeapons;@BuilderItems;@MoreGuns_Test;@CF;"`

Once I did this I was able to connect, and was able to connect to any server I tried with this method.

**Comment by aclist** [comment]
Hmm, interesting. It does make intuitive sense that the parameter given to the `mod` flag should be encapsulated in quotes, rather than the whole string, but the Steam documentation and all information on DayZ mods I could find listed the other option, so I had followed that precedent. When I test it your way on my setup, I am unable to connect to servers, and the mods don't get found correctly. And you were able to get it working with quotation marks on the outside on your other setup, too.

I do believe this is a real issue, and it's probable that other users may be facing it, though.  I'm thinking that the way we are calling the launch options may be malformed, or symlinks are not being interpreted correctly. I'm having a mental block about it at the moment, but will keep investigating this. It seems reasonable to assume that we can replicate the (working) parameters passed manually as launch options. I feel like we are close to figuring this out, so any other observations you can provide are helpful.

The reason I included the debug option was precisely to see if the manual options produce the same, repeatable result. When you said that you pasted the `-connect` and `-mod` flags through the Steam right-click menu, did you omit any options that the script would have created? Are you able to connect if you insert the debug output verbatim into the Steam right-click options?

**Comment by scandalouss** [comment]
I only removed -applaunch as it seemed redundant when launching the game through the steam client. Including it in the launch options didn't change anything.

Pasting the debug options verbatim into the launch options DID result in me loading mods and successfully connecting on both of my machines. This confused me to no end, so I set out on something I planned to do for a little while now.

I reinstalled the base gentoo system on my main computer but kept my home partition and the issue with the quotations in the launch options went away, the game will start with the quotations around either the parameters or the whole -mod string. Pasting the debug line verbatim into the launch options also works still. The script however still doesn't work with the exact same error I started with, and pasting the debug output directly into the terminal produces the same errror.

So I guess I've fixed the issue regarding the quotations around the -mod string, and now the scripts behavior is consistent across both of my machines: cutting the list of mods off at the last space when connecting through either the terminal or the script.

**Comment by aclist** [comment]
I appreciate your sticking with this and for waiting. It takes a little while to debug this, due to having to change the launch options and manually test the result on multiple servers.

Based on your feedback about the word splitting, I think we had a breakthrough:

Basically, the underlying problem is that server operators and mod makers are not consistent about syntax, with some mods using underscores, some using "illegal" characters like apostrophes, and some using spaces. When you pass launch options through Steam's right-click menu, it permits spaces under the hood, then sanitizes these and other characters and escapes them where necessary. When you invoke the Steam browser protocol or launch flags directly on the executable, though, it munges some of these characters and they get malformed.

Even encapsulating the whole thing in quotes via the launch options is not enough here, so I've modified the script to create sanitized symlinks where spaces and illegal characters are replaced by underscores.

As a result, this fixes a longstanding edge case where I was unable to connect to a certain server using a mod called `Cl0ud's Winter Gear`. This apostrophe was getting munged by Steam and causing the whole thing to crash.

I am treating this as a major version change. Please try the latest version of the script, `0.2.0`. You should find that there are no word splitting errors in the terminal now, and the whole mod list will get loaded. The symlink syntax has changed (`@id-mod_name)`, so if you wanted to `unlink` your old symlinks (`@mod name`) from the DayZ directory, you could, but these are just meaningless files, so it won't hurt to leave them. New symlinks will be created. (It might be good to keep both symlink formats to test launch options -- see comments at the end)

What I am still scratching my head about is the V++ server you mentioned specifically. I'm now able to replicate the behavior you mentioned: it loads to about 50% and seems to stall. But the Steam debug output is totally clean. I'm wondering if one of these mods takes a very long time to load, or if it's something unique to this server. I believe the new logic should work on 99% of servers, but would still like to know what is happening here. 

The server in question uses two mods with some characters not typically used: 
- [VPP]DeathMatch
- [VPP]DeathMatchWeapons

and these brackets are being sanitized. I don't think it is failing to find the mods, though, because if the mods were mismatched, the server would kick you without going to the loading screen. The fact that it gets that far and hangs points to something else to me. Do you find it usually takes a long time to load this server's mods?

These are the new options the script generates for that server:
`"-mod=@2565724570-Better_Snap_Sounds;@2444247391-Inventory_Move_Sounds;@2143128974-Advanced_Weapon_Scopes;@1898004795-VPP_DeathMatch;@2563316645-VPP_DeathMatchWeapons;@1565871491-BuilderItems;@2061674116-MoreGuns_Test;@1559212036-CF"`

These are your old options:
`"-mod=@Better-Snap-Sounds;@Inventory Move Sounds;@Advanced Weapon Scopes;@[VPP]DeathMatch;@[VPP]DeathMatchWeapons;@BuilderItems;@MoreGuns_Test;@CF;"`

When pasting these into Steam, do both of these work, or only one? If you kept the old symlinks, either of these should be viable.

**Comment by scandalouss** [comment]
I've tested the updated script, and I believe were on the same page now, exactly. I no longer run into the `line 574: no match: Scopes;@[VPP]DeathMatch;@[VPP]DeathMatchWeapons;@BuilderItems;@MoreGuns_Test;@CF;` error and can connect to every server I've tried with how the mod string is handled now. EXCEPT for any of the V++ servers.

V++ still fails in the same way using the script, loading to about 50% then hanging indefinitely. Both `-mod` strings work when set in the steam launch options, and I can connect successfully to any of the V++ servers that way. Pasting the debug output from the new script into the terminal results in the server hanging at 50%, and you're right about the steam debug output not being very helpful when the server hangs.

When I connect successfully to any of the V++ servers, it does not take a long time to load. It will pause at the same point it does when it hangs, around the 50ish% mark, but only for 5 or so seconds before loading into the main menu.

**Comment by aclist** [comment]
OK, that's an improvement, for a start.

Strangely, I'm not able to connect to VPP whether or not I use the script or the Steam right-click options. I still get the 50% hang in both scenarios, so something seems to be slightly different for us. Can you paste Steam's output when launching the game via the right-click options and through Steam? It should look something like this:

`Game process updated : AppID 221100 "/home/me/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=221100 -- '/home/me/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/me/.local/share/Steam/compatibilitytools.d/Proton-6.21-GE-2'/proton waitforexitandrun  '/media/nvme/games/steamapps/common/DayZ/DayZ_BE.exe' -exe DayZ_x64.exe -nolauncher -nosplash -skipintro -world=empty -connect=51.222.191.212:2302 "-mod=@2565724570-Better_Snap_Sounds;@2444247391-Inventory_Move_Sounds;@2143128974-Advanced_Weapon_Scopes;@1898004795-VPP_DeathMatch;@2563316645-VPP_DeathMatchWeapons;@1565871491-BuilderItems;@2061674116-MoreGuns_Test;@1559212036-CF"", ProcID 834019, IP 0.0.0.0:0`

**Comment by aclist** [comment]
Also, to further narrow down the mod behavior itself:

Under `<steam path>/steamapps/compatdata/221100/pfx/drive_c/users/steamuser/AppData/Local/DayZ` there are a series of `.log` and `.RPT` files with timestamps. Check the most recent pair after successfully connecting to VPP. The `.RPT` file corresponds to the DayZ initialization, and the `.log`corresponds to additional scripts/mods.

Here're my logs when failing at 50%:

(RPT)

```
=====================================================================
== Z:\media\nvme\games\steamapps\common\DayZ\DayZ_x64.exe
== "Z:\media\nvme\games\steamapps\common\DayZ\DayZ_x64.exe" -nosplash -skipintro -world=empty -name=player -connect=135.148.136.66:2402 "-mod=@1999076953-Notes;@1797720064-WindstridesClothingPack;@1618078236-Cl0ud_s_Winter_Gear;@2143128974-Advanced_Weapon_Scopes;@2141780688-ArmA_2_ACR_Weapon_Pack;@2155726353-Mortys_Weapons;@2289461232-Namalsk_Survival;@2110459075-DayOne;@2328820510-Cold_Chernarus;@2560589980-LegacyGunplay;@1597140327-Winter_Chernarus;@1564026768-Community_Online_Tools;@1559212036-CF" -nosplash -skipintro -world=empty -connect=51.222.191.212:2302 -mod=@2565724570-Better_Snap_Sounds;@2444247391-Inventory_Move_Sounds;@2143128974-Advanced_Weapon_Scopes;@1898004795-VPP_DeathMatch;@2563316645-VPP_DeathMatchWeapons;@1565871491-BuilderItems;@2061674116-MoreGuns_Test;@1559212036-CF
=====================================================================
Exe timestamp: 2021/12/08 15:32:20
Current time:  2021/12/31 09:31:02

Version 1.15.154355
 9:31:02.441 [Inputs] Loading inputs default "bin/constants.xml"
 9:31:02.444 [Inputs] Loading inputs default "bin/specific.xml"
 9:31:02.444 [Inputs] Loading inputs default "VanillaPPMap/data/modded_Inputs.xml"
 9:31:02.445 [Inputs] Loading inputs default "VPPAdminTools/data/modded_Inputs.xml"
 9:31:02.446 [Inputs] Loading inputs default "InventoryMoveSounds/Scripts/Data/Inputs.xml"
 9:31:02.447 [Inputs] Loading inputs default "VPPDeathmatch/data/modded_Inputs.xml"
 9:31:02.448 [Inputs] Loading inputs cfg "C:\users\steamuser\Documents\DayZ\steamuser.core.xml"
 9:31:02.453 [Inputs] Exporting inputs cfg "C:\users\steamuser\Documents\DayZ\steamuser.core.xml"

```

(.log)
```
---------------------------------------------
Log C:\users\steamuser\AppData\Local\DayZ\script_2021-12-31_09-31-00.log started at 31.12. 09:31:02

SCRIPT       : Registered 265 temporary action enum(s), UAN==265
SCRIPT       : CF_CreateGame()
SCRIPT       : ... Backlit Effects Enabled
SCRIPT       : DZM_Projects Map! by DaOne
SCRIPT       : VPPNotificationManager()
SCRIPT       : [VPPAT] Internal VPPNotifications module loaded!
SCRIPT       : [DayZ Game]:: DayZGame(): Initializing V++ Admin Tools.
SCRIPT       : $saves:VPPDummyMissions/Dummy.ChernarusPlus/init.c  DELETED IN SAVES.
SCRIPT       : $saves:VPPDummyMissions/Dummy.Enoch/init.c  DELETED IN SAVES.
SCRIPT       : $saves:VPPDummyMissions/Dummy.namalsk/init.c  DELETED IN SAVES.
SCRIPT       : $saves:VPPDummyMissions/Dummy.swansisland/init.c  DELETED IN SAVES.
SCRIPT       : $saves:VPPDummyMissions/Dummy.zargabad/init.c  DELETED IN SAVES.
SCRIPT    (W): @"CPBWeapons\Scripts\4_World/m14.c,82": Missing ';' at the end of line
SCRIPT    (W): @"CPBWeapons\Scripts\4_World/m14.c,82": Missing ';' at the end of line
SCRIPT    (W): @"CPBWeapons\Scripts\4_World/val.c,82": Missing ';' at the end of line
SCRIPT    (W): @"CPBWeapons\Scripts\4_World/val.c,82": Missing ';' at the end of line
SCRIPT    (W): @"CPBWeapons\Scripts\4_World/cpbvss_base.c,82": Missing ';' at the end of line
SCRIPT    (W): @"CPBWeapons\Scripts\4_World/cpbvss_base.c,82": Missing ';' at the end of line
SCRIPT       : [ DayZGame ] Start Dummy Mission for client...
SCRIPT       : string missionPath = ''
```

I'd be interested to see if this differs on a successful load. I don't think the lines above are errors, though. They appear to be warnings about syntax.

**Comment by scandalouss** [comment]
Here is my steam output when running the game:

`Game process updated : AppID 221100 "/home/david/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=221100 -- '/home/david/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/david/.local/share/Steam/compatibilitytools.d/Proton-6.21-GE-2'/proton waitforexitandrun  '/home/david/.local/share/Steam/steamapps/common/DayZ/DayZ_BE.exe' -exe DayZ_x64.exe  -connect=51.222.191.212:2302 -nolauncher -nosplash -skipintro -world-empty "-mod=@2565724570-Better_Snap_Sounds;@2444247391-Inventory_Move_Sounds;@2143128974-Advanced_Weapon_Scopes;@1898004795-VPP_DeathMatch;@2563316645-VPP_DeathMatchWeapons;@1565871491-BuilderItems;@2061674116-MoreGuns_Test;@1559212036-CF"", ProcID 8008, IP 0.0.0.0:0
`

Here are the logs you requested from a successful connection:

.log:
```---------------------------------------------
Log C:\users\steamuser\AppData\Local\DayZ\script_2021-12-30_21-04-26.log started at 30.12. 21:04:27

SCRIPT       : Registered 265 temporary action enum(s), UAN==265
SCRIPT       : CF_CreateGame()
SCRIPT       : ... Backlit Effects Enabled
SCRIPT       : DZM_Projects Map! by DaOne
SCRIPT       : VPPNotificationManager()
SCRIPT       : [VPPAT] Internal VPPNotifications module loaded!
SCRIPT       : [DayZ Game]:: DayZGame(): Initializing V++ Admin Tools.
SCRIPT       : $saves:VPPDummyMissions/Dummy.ChernarusPlus/init.c  DELETED IN SAVES.
SCRIPT       : $saves:VPPDummyMissions/Dummy.Enoch/init.c  DELETED IN SAVES.
SCRIPT       : $saves:VPPDummyMissions/Dummy.namalsk/init.c  DELETED IN SAVES.
SCRIPT       : $saves:VPPDummyMissions/Dummy.swansisland/init.c  DELETED IN SAVES.
SCRIPT       : $saves:VPPDummyMissions/Dummy.zargabad/init.c  DELETED IN SAVES.
SCRIPT    (W): @"CPBWeapons\Scripts\4_World/m14.c,82": Missing ';' at the end of line
SCRIPT    (W): @"CPBWeapons\Scripts\4_World/m14.c,82": Missing ';' at the end of line
SCRIPT    (W): @"CPBWeapons\Scripts\4_World/val.c,82": Missing ';' at the end of line
SCRIPT    (W): @"CPBWeapons\Scripts\4_World/val.c,82": Missing ';' at the end of line
SCRIPT    (W): @"CPBWeapons\Scripts\4_World/cpbvss_base.c,82": Missing ';' at the end of line
SCRIPT    (W): @"CPBWeapons\Scripts\4_World/cpbvss_base.c,82": Missing ';' at the end of line
SCRIPT       : [ DayZGame ] Start Dummy Mission for client...
SCRIPT       : string missionPath = '$saves:VPPDummyMissions\Dummy.ChernarusPlus'
SCRIPT    (W): @"VPPAdminTools/5_Mission/vppadmintools\freecamera.c,59": Unsafe down-casting, use 'DayZPlayerCameraBase.Cast' for safe down-casting
SCRIPT    (W): @"VPPDeathmatch/5_Mission/VPPDeathmatch/client/HalfTimeScene/ЭШТџ?зелТ.ogg,40": Unsafe down-casting, use 'DayZPlayerCameraBase.Cast' for safe down-casting
SCRIPT       : Vanilla++ AdminTools Plugins Registering..
SCRIPT       : Creating ModuleManager
SCRIPT       : CF_CreateWorld()
SCRIPT       : Modules Loaded
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "gaspingForAirEmpty_SoundVoice_Char_SoundSet".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "greathelmet_gaspingForAirEmpty_SoundVoice_Char_SoundSet".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "Motohelmet_gaspingForAirEmpty_SoundVoice_Char_SoundSet".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "Gag_gaspingForAirEmpty_SoundVoice_Char_SoundSet".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "gaspingForAir5perIdle_SoundVoice_Char_SoundSet".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "greathelmet_gaspingForAir5perIdle_SoundVoice_Char_SoundSet".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "Motohelmet_gaspingForAir5perIdle_SoundVoice_Char_SoundSet".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "Gag_gaspingForAir5perIdle_SoundVoice_Char_SoundSet".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "gaspingForAir10perIdle_SoundVoice_Char_SoundSet".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "greathelmet_gaspingForAir10perIdle_SoundVoice_Char_SoundSet".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "Motohelmet_gaspingForAir10perIdle_SoundVoice_Char_SoundSet".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "Gag_gaspingForAir10perIdle_SoundVoice_Char_SoundSet".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "generalgrunt_SoundVoice_Char_SoundSet".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "greathelmet_generalgrunt_SoundVoice_Char_SoundSet".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "Gasmask_generalgrunt_SoundVoice_Char_SoundSet".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "Motohelmet_generalgrunt_SoundVoice_Char_SoundSet".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "Gag_generalgrunt_SoundVoice_Char_SoundSet".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "walkProne_noHS_gravelSmall_ext_Char_Soundset".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "walkProneLong_noHS_gravelSmall_ext_Char_Soundset".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "dirt_ext_drop_Soundset".
SCRIPT       : AnimSoundObjectBuilderBank: Invalid sound set "asphalt_ext_drop_Soundset".
SCRIPT       : [SubscriptionDataCb] !!! OnError() EREST_ERROR_APPERROR
SCRIPT       : SteamAccountSyncCb --> 0
SCRIPT       : [LobbyMission] OnMissionFinish() destroying hive: Hive<a5ccf5f0>
SCRIPT       : ~DayZGame()
```


.RPT:
```=====================================================================
== Z:\home\david\.local\share\Steam\steamapps\common\DayZ\DayZ_x64.exe
== "Z:\home\david\.local\share\Steam\steamapps\common\DayZ\DayZ_BE.exe" -exe DayZ_x64.exe -connect=51.222.191.212:2302 -nolauncher -nosplash -skipintro -world-empty -mod=@2565724570-Better_Snap_Sounds;@2444247391-Inventory_Move_Sounds;@2143128974-Advanced_Weapon_Scopes;@1898004795-VPP_DeathMatch;@2563316645-VPP_DeathMatchWeapons;@1565871491-BuilderItems;@2061674116-MoreGuns_Test;@1559212036-CF
=====================================================================
Exe timestamp: 2021/12/26 19:41:17
Current time:  2021/12/30 21:04:27

Version 1.15.154355
21:04:27.191 [Inputs] Loading inputs default "bin/constants.xml"
21:04:27.194 [Inputs] Loading inputs default "bin/specific.xml"
21:04:27.194 [Inputs] Loading inputs default "VanillaPPMap/data/modded_Inputs.xml"
21:04:27.195 [Inputs] Loading inputs default "VPPAdminTools/data/modded_Inputs.xml"
21:04:27.196 [Inputs] Loading inputs default "InventoryMoveSounds/Scripts/Data/Inputs.xml"
21:04:27.196 [Inputs] Loading inputs default "VPPDeathmatch/data/modded_Inputs.xml"
21:04:27.197 [Inputs] Loading inputs cfg "C:\users\steamuser\Documents\DayZ\steamuser.core.xml"
21:04:27.201 [Inputs] Exporting inputs cfg "C:\users\steamuser\Documents\DayZ\steamuser.core.xml"
21:04:50.32 !!! File "\cfgenvironment.xml" does not exist...
21:04:50.743 [CE][Hive] :: Initializing SANDBOX
21:04:50.743 [CE][Hive] :: Loading core data ... 
21:04:50.743 !!! File "\cfgeconomycore.xml" does not exist...
21:04:50.743 !!! [CE][CoreData] :: ZERO root classes - SPAWN WILL NOT WORK
21:04:50.752 !!! File "\cfgplayerspawnpoints.xml" does not exist...
21:04:50.755 !!! File "\cfgspawnabletypes.xml" does not exist...
21:04:50.755 [CE][RegisterBind] :: 0 classes binded...
21:04:50.755 [CE][RegisterConfig] :: 1 config classes registered, 0 sub-counters...
21:04:50.755 [CE][Hive] :: Loading map data ... 
21:04:50.756 !!! File "\cfglimitsdefinition.xml" does not exist...
21:04:50.756 !!! File "\cfglimitsdefinitionuser.xml" does not exist...
21:04:50.756 !!! [CE] :: Failed to read '\cfglimitsdefinition.xml' file.
21:04:50.756 !!! File "\mapgroupproto.xml" does not exist...
21:04:50.756 !!! File "\mapclusterproto.xml" does not exist...
21:04:50.756 !!! File "\areaflags.map" does not exist...
21:04:50.756 !!! File "\mapgrouppos.xml" does not exist...
21:04:50.756 !!! File "\mapgroupdirt.xml" does not exist...
21:04:50.756 [CE][Links] found 0 total links between groups, of 0
21:04:50.756 [CE][LoadClusters] "Cluster" :: Loading files...
21:04:50.756 !!! File "\mapgroupcluster.xml" does not exist...
21:04:50.757 [CE][Storage] ver:21 stamp:31, valid:yes, name:"C:\users\steamuser\Documents\DayZ\VPPDummyMissions\Dummy.ChernarusPlus\storage_-1\data\types.bin"
21:04:50.757 [CE][Storage] ver:21 stamp:27, valid:yes, name:"C:\users\steamuser\Documents\DayZ\VPPDummyMissions\Dummy.ChernarusPlus\storage_-1\data\types.001"
21:04:50.757 [CE][Storage] ver:21 stamp:28, valid:yes, name:"C:\users\steamuser\Documents\DayZ\VPPDummyMissions\Dummy.ChernarusPlus\storage_-1\data\types.002"
21:04:50.757 [CE][Storage] Restoring file "C:\users\steamuser\Documents\DayZ\VPPDummyMissions\Dummy.ChernarusPlus\storage_-1\data\types.bin".
21:04:50.758 [CE][offlineDB] :: Loaded 0 dynamic events 0 total types.
21:04:50.759 [CE][Storage] ver:21 stamp:31, valid:yes, name:"C:\users\steamuser\Documents\DayZ\VPPDummyMissions\Dummy.ChernarusPlus\storage_-1\data\events.bin"
21:04:50.759 [CE][Storage] ver:21 stamp:27, valid:yes, name:"C:\users\steamuser\Documents\DayZ\VPPDummyMissions\Dummy.ChernarusPlus\storage_-1\data\events.001"
21:04:50.759 [CE][Storage] ver:21 stamp:28, valid:yes, name:"C:\users\steamuser\Documents\DayZ\VPPDummyMissions\Dummy.ChernarusPlus\storage_-1\data\events.002"
21:04:50.759 [CE][Storage] Restoring file "C:\users\steamuser\Documents\DayZ\VPPDummyMissions\Dummy.ChernarusPlus\storage_-1\data\events.bin".
21:04:50.759 [CE][DynamicEvent] Load  Events:[0] Primary spawners: 0 Secondary spawners: 0
21:04:50.759 [CE][Hive] :: Empty storage folder, reinitializing ... 
21:04:50.759 [CE][Hive] :: Initializing ... 
21:04:50.763 [CE][InitializeMap] :: initialized: 0
21:04:50.763 [CE][Hive] :: Initializing spawners ... 
21:04:50.763 !!! File "\cfgeventspawns.xml" does not exist...
21:04:50.763 [CE][DE] :: Total positions: 0
21:04:50.763 [CE][DynEvent] :: 0 types
21:04:50.763 [CE][Hive] :: Initializing of spawners done.
21:04:50.764 [CE][Hive] :: Init sequence finished.
21:04:53.694 Player connect enabled
21:05:00.350  --- Termination successfully completed --- 
```

I see this in your .log: `SCRIPT       : string missionPath = ''` where it hangs, but in my .log its: `SCRIPT       : string missionPath = '$saves:VPPDummyMissions\Dummy.ChernarusPlus'`

**Comment by aclist** [comment]
Thank you. I reinstalled the VPP mods as a test, but that wasn't it.

I see some discrepancies between the logs, such as that you mistyped the `-world=empty` parameter as `world-empty`, and I was hoping this would be the smoking gun, but it did not change anything. This is merely a performance improvement to speed up loading.

I neglected to ask you: 
- When you launch DayZ manually from Steam, are you selecting the first option ("Play DayZ"), or the second option ("Run DayZ client")?
- Which version of Proton do you have this currently bound to?

Sorry for all the questions. Progress is being made...

**Comment by scandalouss** [comment]
Oops haha I fixed the typo, was going fast... When I launch the game from steam I select the second option, and I'm using Proton-6.21-GE-2. I don't run into any differences running on Proton 6.3-8 if that means anything.

Normally I only include `-connect` and `-mod` in the launch options as the other options never seemed to improve loading times for me, but I included them to see if that was causing issues.

**Comment by aclist** [comment]
> Normally I only include -connect and -mod in the launch options as the other options never seemed to improve loading times for me, but I included the other launch options in the script to see if that was causing issues.

This was an absolutely critical detail. It's fixed. Details follow.

First, regarding the `-nolauncher` flag, it is functionally equivalent to selecting "Run DayZ client," so it is important to have. I understand that Proton 7 and later has fixed the crash with the first option "Play DayZ," but I haven't tested that yet, and it would break backwards compatibility with other Proton versions, requiring the user to stick to Proton 7, so for now I think including this flag is appropriate.

As for the issue: the `-world=empty` flag was causing the problem, and it was working for you because you had omitted some of the launch parameters, including that one. Explanation: the VPP server uses a custom menu before loading the game. This flag eliminates the world map on the main menu and back-loads the process of loading assets until you load into the map. Using this was effectively killing the special main menu that custom servers like VPP provide before the game itself.

So, I removed that option, and everything seems to be working now. There wasn't much point to that option, anyway, as it pushes the load time to when you zone into the map, so it's not really a performance fix, so far as I can see. We can safely remove this without affecting other server types, as well. So far, so good.

The new version `0.2.1` includes this fix; give it a try and you should be able to load into VPP after a brief pause.

I'd like to recognize your contributions to this fix by including a credit in the script, or by buying you a Steam game. Up to you.

**Comment by scandalouss** [comment]
Everything is working now! Interesting that `-world=empty` was the culprit, I wish that was something the mod authors would specify on the mods download page.

You don't have to buy me anything! A simple credit is fine if that's what you wanna do. 

I suppose we can consider this issue closed now, I no longer have any issues connecting to any server with the script, it's working great now.

**Comment by aclist** [comment]
That's great. Let me know if you need anything else later. Have a happy new year!

**Comment by aclist** [comment]
Resolved by https://github.com/aclist/dztui/commit/30ba0c1c8ce7d7447b7ed9e7f7239664ab242d1f
