### ISSUE TITLE
White list error after first launch

### ISSUE THREAD

**Issue by Whippy77** [aclist/dztui#20]
Just tried to get this working and keeps coming up with Error: error in key Whitelist. Any ideas how to reset this or why this is happening? I’ve put in my API key etc! But never got a server list up and now this warning. it was DZGUI. I did put a server ID found from battle metric. Followed the instructions and believe latest version of the launcher. Can’t do anything as warning comes up every time I try to launch it. Also can’t find the config file at all and I’ve tried everything. All done on Steam Deck.

**Comment by aclist** [comment]
From the description, it looks like you pasted in unsanitized text, probably containing a line break, into the server field and it got split, since it's getting as far as the API key check. 

I've released a hotfix version which gives the user the option to re-run first time setup if their config file is malformed due to user error, and included additional checks of input fields to prevent the user from typing in invalid text. Next time you run the application, it will prompt you to download version `2.3.1`, and once you run it, it will ask you to regenerate your configs if they are broken.

**Comment by Whippy77** [comment]
Yeah I managed to get it working. Unfortunately I then downloaded the new version and now when I execute I get “Unknown Error code 100 execvp: exec format error. Any ideas now? I had it working too 😫

**Comment by aclist** [comment]
It's not a bug in the application; seems to be pointing to the OS's desktop environment and how it launches files. How are you launching this program, exactly?

**Comment by aclist** [comment]
This seems to be an obscure issue with the KDE desktop environment, on which the SD runs, when it tries to launch a non-executable file with an executable bit that shouldn't be there, or when trying to launch applications through shortcuts.

- Are you using SD in Desktop or Gaming mode?
- Where are you launching the file from?
- Did you also install Windows or NTFS partitions on this device?
- Did you add the file as a non-Steam game into the Steam interface?
- Did you change the executable flags on the file?
- Are you trying to double click the file to run it?

I have a SD but don't have a dock for it at the moment, so it'll take me some time to reproduce this.

**Comment by Whippy77** [comment]
Using it in desktop mode. Launching from where I extracted it into (downloads). Only just got it so no Windows and never intend to install it. I did it once but deleted it as wouldn’t run in gaming mode. Will that work? I do double click it to run it. 
i have reverted back to old version now which appears to be working so far since I changed the server ID into right column on Config. Hope that makes sense.

**Comment by Whippy77** [comment]
I definitely put it in the right column on first launch so no idea why it was put in wrong column as if I hadn’t put a server ID in. It Basically went At end of the API key

**Comment by aclist** [comment]
I'll think about this and try to reproduce it. Double clicking a script rather than invoking it directly can produce a lot of unintended outcomes depending on how the desktop environment widget handles it.

Yes, it can be added to SD by adding a generic program in Desktop mode and then editing the launch options to point to it. I'd have to put up a tutorial. I do think that letting the shell launch the app directly from Steam would be less error-prone. 

Nothing fundamental changed under the hood with this minor version bump, so I'm scratching my head, but will try to replicate the bug. When you say downloaded, did you download the new version manually, or through the app?

Steam Deck support is more of a side effect than a deliberate feature, since SD is an experimental piece of hardware for enthusiasts. I'm targeting a desktop environment first and foremost for compatibility, so can't test every feature on mobile, but this should change once I get a dock.

Re: server ID, interally, the table splits the fields on a delimiter, so if there was an invisible line break before or after the text entered, it could shift the fields over and cause them to get parsed out of alignment. The hotfix introduces stricter error regex string parsing to prevent entries which are empty or not numerical.

**Comment by aclist** [comment]
OK, this was bugging my curiosity, so I painstakingly worked on the Steam Deck with the onscreen keyboard and got the script. 

Yeah, it's exactly what I hypothesized: this is a side effect in KDE's Dolphin file manager in the way it handles executable scripts launched from a click in the file explorer context menu. This doesn't behave the same way as invoking a script literally in the shell. 

In general, it's not advisable to double-click to launch scripts unless they have a very defined functionality such as do one thing and exit. They're not exactly analogous to binary executable files, and are interpreted at runtime. If Dolphin has some internal handling for .sh files that doesn't process them as intended, it's going to lead to weird and unexpected behavior, such as one version of the application working and one not.

I would advise invoking it directly in the terminal as `./dzgui.sh` or by creating a standalone shortcut that then launches the script. When you click to launch the script as though it were itself a shortcut, it doesn't produce the expected behavior, because it's trying to run the script through whatever weird subshell Dolphin itself imposes.

I did briefly test with adding it as a non-Steam game, and this works in Gaming mode as well, although the launch parameters have to be correctly formed, so I'll do some testing on that. Ideally, we could ship a premade shortcut or installer with box artwork. I need to look into the spec Steam uses for .desktop file shortcuts.  

I would always advise you to stay up to date on the latest version and not intentionally avoid upgrading unless there is a blocking regression. Regressions do get hotfixed, so it's useful to follow the update cycle and download, because it introduces important bug fixes and QOL features.

**Comment by Whippy77** [comment]
Ok will update next time I’m on. Won’t double click but have a feeing I will still see the error code 100 appear again. I thought it was it’s own shortcut! It looks like one! But thanks for looking into all this especially on SD. These things are here to test us all lol

**Comment by aclist** [comment]
I have tested it and I can assure you that the error will not appear again if you invoke it correctly. By the end of the weekend, if not sooner, I will push an update that auto-deploys a working shortcut with icon to the desktop. Thanks for your patience.

**Comment by aclist** [comment]
OK, think we have something ready to go now. I have a whole suite of changes ready to go on the Testing branch, but I want you to try it out before we deploy it to everyone. I was going to merge these changes to the mainline branch so that you could just upgrade in one go, but I thought better of it because of the possibility of breaking changes.

I tested this end to end on a Steam Deck, upgrading from Stable (2.3.3) to Testing (2.4.0-rc.14) of DZGUI and getting al shortcuts and everything working on Gaming and Desktop mode.

Can you please do the following?

1. Launch the app as you usually would with your current version
2. From the main menu, select "Toggle debug mode"
3. This will expose a "Debug options" menu at the bottom of the list
4. Enter that option and select "Toggle branch"
5. This will take a moment while it pulls down the Testing branch
6. Exit the app and restart it manually from the terminal
7. Note the header now lists the version as "2.4.0-rc.14",  the branch as "testing", and the mode as "debug"
8. Note that a shortcut was added to the desktop. The icon image might take a moment to sync/update. After you relaunch the app a few times, it should stick. That's a Steam Deck limitation, not mine.
9. There is also a shortcut under the Start menu > Games > DZGUI
10. Verify that the shortcut works as intended
11. You can just launch directly via these shortcuts now. The program makes a copy of itself elsewhere in the system and binds to the shortcuts
12. At this point, you should select the "Toggle debug mode" option in the main menu again so that you go into normal mode and can connect to servers. Make note that the header has updated to say "Mode: normal"

To add the shortcut directly to Steam so that it can be used in Gaming mode, follow these instructions that I added here: https://aclist.github.io/dzgui/dzgui.html#_steam_integration_artwork

I also bundled custom artwork and covers so that you can get a visual card in your Steam library (shown in documentation).

!! NOTE: You should not need to switch versions manually again, but if you do decide to roll back versions (i.e. toggle branch to stable again), do NOT do so from within the testing version or via the shortcut (use the old copy of the script instead). The desktop shortcut is bound to the testing version logic, and will break if you roll back to the older version that does not have this shortcut logic built into it yet. Until I merge these changes into the mainline branch, it will not be possible for the old (2.3.3) version to bootstrap itself. This should only be a temporary limitation until I merge the testing branch into the stable branch following your confirmation that the above is all working.

Thanks. Anything unclear, please ask.

**Comment by Whippy77** [comment]
Ok I’ll boot it up today and let you know.

**Comment by Whippy77** [comment]
Yes, did it all. Short cut works lovely! So Much better! Thank you very much. :)
Launched into Namalsk no issues. Will add shortcut to gaming mode now 👍🏻

**Comment by aclist** [comment]
Great, thanks! I'll merge this into mainline tomorrow and notify you, after which point it should become safe to toggle branches back and forth.

**Comment by Whippy77** [comment]
Brilliant. Re using launcher in gaming mode, if you hold the Steam button, mouse will work fine for navigating around launcher! Only found that out recently. Very handy for Discord where I was tapping touchscreen to navigate lol

**Comment by aclist** [comment]
Cool, didn't know that. My screen is filthy from tapping

**Comment by aclist** [comment]
OK, update is live on both Stable and Testing. You should be able to toggle back to the stable branch and freely jump between them without damage.

**Comment by Whippy77** [comment]
Last question and I’ll leave you be. Do I need to change back? Will I still get any future updates? I still have testing branch but not sure how to toggle to stable.

**Comment by aclist** [comment]
The two branches have a different release cadence and purpose:

Stable: more conservative release schedule, receives critical updates, but new features are only rolled out after elaboration on the Testing branch
Testing: continuous update cadence, receives work in progress updates testing new features, more of a playground for beta testing

It comes down to your personal risk tolerance. Both will receive updates, and you can switch between them at will. I do need more testers, but it's up to you.

The Testing branch is hidden by default so that users do not inadvertently enable it if they don't want to. 

To switch to Stable, reverse the process above:

- Toggle debug mode from main menu
- Open Debug options at bottom of list
- Select Toggle branch
- This will swap you to Stable and force the app to download the Stable version
- Toggle debug mode again to return to normal mode and allow connecting to servers (debug mode is used for dry runs)
- Currently, Stable and Testing are on the same code, so there is no functional difference as of this writing

Main thing I would keep an eye out for if you are using a Steam Deck is the size of notification windows. I noticed that a few of them got oddly resized on the SD, so I fixed the ones I could find, but there might be a few others that are squashed.

**Comment by Whippy77** [comment]
Brilliant, I’ll keep it in testing then! I only play PC on Steam Deck currently as I like the console experience.

**Comment by aclist** [comment]
Interesting. Are you using that directly on the device, or do you connect it to an external screen?

**Comment by Whippy77** [comment]
Mainly on device but have connected it to TV.

**Comment by aclist** [comment]
OK, neat. I'm guessing some of the menus look a bit shabby when scaled at that size? (Out of our control)

**Comment by aclist** [comment]
Yeah, I hope they will give us the ability to scale UI elements for system applications in the future without having to write a whole Steamworks application.

By the way, I had a little eureka moment about a possible way of controlling the DZGUI interface on the Steam Deck, but I'm not sure if it's totally viable: I was playing around with creating a controller template that lets you navigate around the menu and select/go back using the keys on the device rather than the touchscreen. The idea is to upload this to the community controller configs as the official DZGUI template.

The problem I see here is that once you launch DayZ, it's not getting its own controller template, as it's technically a child of the DZGUI process. So you'd be stuck with the controller settings defined for the launcher when you are in the game, unless you started to do some fancy rebinding inside of DayZ.

Maybe there's a way to combine these two ideas by reserving a couple keys on the Steam Deck for the launcher, and leaving the rest for the game? Maybe using the D-pad to move through the launcher menu? I'm not really sure what would work well here, since I don't play on SD. 

What keybindings do you use? Do you just control DayZ with the default "gamepad with joystick" layout out of the box?

**Comment by Whippy77** [comment]
When DayZ loads up via your launcher or the main game in Game Mode SteamOS remembers your last saved key bindings for that game. Which you can of course edit whenever you like even in game. I use a community layout and added my own keybindings which it remembers. There are of course official layouts but have a lot of important keys missing. They don’t seem to have the Xbox DayZ control layout on it yet! Maybe when it becomes verified. I navigate perfectly fine using the mouse via touchpad even in docked. I think the ps4 touchpad even works due to SteamOS overlay but would need to check.

**Comment by aclist** [comment]
I think I have a solution that could be built on top of a normal DayZ config: https://partner.steamgames.com/doc/features/steam_controller/action_set_layers

Basically, add a hidden layer with navigation keys for the launcher. You activate it by long-holding some button for a predetermined amount of time (e.g. 5 seconds) or by chording some buttons together (e.g. A + B + X + Y) and then you are in "DZGUI navigation mode," which lets you do stuff with the menu. Then invoke the magic key again to go back to your normal bindings.

I'll prototype that a bit. I know the touchpad is viable, but it's a little finicky due to the small size. I found that using the D-pad was pretty good, as it activates an actual highlight over your currently selected row and makes moving around pretty snappy.
