### ISSUE TITLE
[BUG] After 10th server table gets unformated

### ISSUE THREAD

**Issue by lescuer97** [aclist/dztui#21]
**Info**
DZGUI version:2.4.0
Mode (normal/debug):normal
Server ID: nono
Linux distribution: popos

**Bug description**
tried to add 10 servers to the list and got a weird formating error. 
![serverlis](https://user-images.githubusercontent.com/47948594/183768751-a932cc1b-bf11-4e02-bb80-efb9f63efbc2.png)

**To Reproduce**
1. Add 9 servers to the app
2. add a 10th one
3. try to list the servers for listting
4. you'll see the wrong formating

**Expected behavior**
the list should continue like when there is 9 servers listed: 
![correct_list](https://user-images.githubusercontent.com/47948594/183769038-326b3169-78eb-4a94-957e-681c822e920b.png)

Extra Info this are the ids of the servers that I tried for 10th on the list:
- 15082587  
- 15538153
- 15266545

I don't know if this has to do with the long title or something like that

**Comment by aclist** [comment]
Thanks for reporting that. I pushed a hotfix (`2.4.1`).

The table expects a specifically formatted array format, but the progress of that is also sent to the pulsating progress bar so we can see a real-time list of how many servers we checked (1/10...2/10...etc) before loading the table. Some extra debug code in the array creation function was leaking into the progress bar and pushing everything over. When there were greater than 9 items in the list, the progress bar failed, which caused the array creation function to exit unintentionally, and the data destined for the table was not aligned as expected.

I changed it so that the progress bar only gets visual progress info and extra stuff doesn't leak into it.
