### ISSUE TITLE
[BUG] Certain mods not loaded when joining modded server

### ISSUE THREAD

**Issue by t1337dude** [aclist/dztui#24]
I'm using the current stable released of dzgui on the latest Steam Deck build. When trying to join the [Sunnyvale #15](https://www.battlemetrics.com/servers/dayz/16147207) server, I run into an error saying that certain mods aren't loaded ([screenshot](https://i.imgur.com/RilY37Q.png)). I can see that the mods are properly downloaded and the "link" is properly created, but once I'm in the game, it seems only ~40/44 of the mods load. I can verify that the mods aren't loaded when I click the ingame mod list and see that they are missing. Thank you for your time.

EDIT: One more observation that might be worth noting is that the mods not loading are the ones sharing same-name but different-casing @ tag folder links. I can verify this explicitly in the debug mode where it lists which mods are loaded.

For example, `@lg` is loaded but `@Lg` isn't. Similarly `@XA` is loaded, but `@xA` is not. From my eyes it appears that whichever script builds the list of mods to be loaded is having a hangup, and I can only assume it's failing to differentiate between uppercase and lowercase letters in the tags.

**Comment by aclist** [comment]
Thanks for the report. Only happens on this server? I'll try to investigate.

Please do me a favor:

1. From the main menu, select Toggle debug mode
2. Select the new Debug options entry at the bottom of the list
3. Select Generate debug log
4. A file called "log" should be generated under $HOME/.local/share/dzgui
5. Open the file and paste its contents here
6. When finished, select Toggle debug mode again to return to normal mode

Thanks.

**Comment by aclist** [comment]
By the way, since you are a Steam Deck user, let me ask you: would it be beneficial to have an official DZGUI controller template that contains a layer for the launcher menu? Essentially, you would long-hold a certain key and it would switch the input to using the D-pad to navigate the menus and A/B to move forward and back. Then it could be toggled off to revert to the normal control scheme for the game itself.

**Comment by aclist** [comment]
Based on the information you listed above, that seems to be the correct hypothesis. The script is doing its what it should be, but Windows is case-insensitive about paths, so we need a slightly different algorithm for encoding mod names to avoid these collisions. I'll look into it further when I'm back at my desk.

**Comment by t1337dude** [comment]
Here is the requested log.
```
Version: 2.4.1
Branch: stable
Whitelist: 16147207,15619943
Path: /home/deck/.local/share/Steam
Linux: Linux 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3 x86_64

Mods:
BaseBuildingPlus	@_aW]t4Oi
BBPItemPack	@Qw
BodyBags	@QA
BuildingsMegaModPack	@Lg
CabinZ	@Vw
CannabisPlus	@_bOMlL2S
CarCover	@jA
CarePackages Helicopter Licensed	@Dw
Care Packages V3	@Xw
CF	@_Zy7u4CE
CJ187-MoreMoney	@_biVnKSM
Cl0ud's Military Gear	@_aGNo6eh
Code Lock	@_aKHrZOq
[CrSk] BMW 525i E34	@_a]ZsIK4
[CrSk] VAZ-2107	@_ayasZav
Dabs Framework	@IA
DayZ Editor Loader	@lw
DayZ-Expansion-Animations	@3g
DayZ-Expansion-Core	@XA
DayZ-Expansion-Market	@Fg
DayZ-Expansion-Name-Tags	@yA
DayZ-Expansion-Weapons	@7Q
Dogtags	@eg
DrugsPLUS	@gw
FlipTransport	@_a2Oj4K3
Flying Birds!	@1Q
gebsfish	@_Q
GoreZ	@_aKSlIOF
InventoryPlus	@_Z2usY6Z
MuchCarKey	@_bqIlLWo
MuchStuffPack	@_batj5io
PvZmoD_CustomisableZombies	@_bqSubKz
RedFalcon Flight System Heliz	@1A
RedFalcon Mosquito Mk III	@6w
RevGuns	@mw
SNAFU_Weapons	@xA
Sunnyvale_Chernarus	@Fw
Sunnyvale_Original	@dw
Sunnyvale_Original_II	@AA
Sunnyvale_PVE	@Cg
Sunnyvale_PVP	@Ow
Tactical Flava	@lg
TF:Fireworks	@EQ
Vehicle3PP	@_b6gg6az
VPPAdminTools	@_ay]vJGU
WindstridesClothingPack	@_auJsKCA
```
In reply to your second post, I've only played DayZ while using my Steam Deck while docked (with a mouse & keyboard). Having said that, it sounds like good idea and I'm sure there are other Steam Deck users who would appreciate it. Thanks again for the rapid response.

**Comment by aclist** [comment]
Sorry I didn't give you instructions on how to do the workaround you found above; I was walking out the door when you sent your ticket.

Yes, as you discovered, the symlinks are essentially just arbitrary mappings to the real mods, so the names of the symlinks can be anything, provided they are unique and don't contain certain illegal characters.

To give you a top-level synopsis of the issue, there is a bug in the Linux version of the Steam client that was reported in 2018 and has not been fixed: it prevents sending long concatenations of launch parameters that exceed 931 characters, IIRC. Due to the sheer amount of mods some servers load and the lengthy names they have, this quickly adds up fast. We needed some way of minifying the mods into arbitrary UUIDs to distinguish them from each other but slim down the length to something that will fit in the launch options. 

The method being used was too aggressive and was compacting some symlink names into ones that collided with each other. So, I went and pulled the complete list of 28,000 mods and their appids to find an approach that would not produce collisions on any, while still not using their original IDs, because those are too long. The result increases the length of the symlinks a bit, but it's still shorter than the original IDs, and should support upwards of 80 mods on a server before hitting the character limit.

I pushed a hotfix on the Testing branch. Can you test it? You can toggle branches the same way you enabled the hidden debug options before. From inside that sub-menu, select "Toggle branch" to fetch the Testing version. It will download the correct version. There are a couple other backend fixes on the Testing branch that haven't made it to Stable as well.

**Comment by t1337dude** [comment]
I appreciate the rapid support. I also appreciate that you're very open
about how you conduct your work. I know some Python and Java from college
and took a peak at your code and and found it very interesting. It looked
familiar to Python and Java but I didn't recognize what code it's written
in. The Steam Deck is my first chance to experiment with Linux and I find
everything I've learned so far to be very fascinating. I'm also new to
Github and find the site very cool as well.

 I had a brief chance to try the testing branch and tested a couple
different servers. *Worked perfectly during my brief testing*. If there's
anything else that comes up, I'll do my best to document it and let you
know. I'll also be sure to spread the good word about your program, because
I had to look around a little while before I found it (one person mentioned
it on the DayZ page on Protondb). Thanks again!

**Comment by aclist** [comment]
>  It looked familiar to Python and Java but I didn't recognize what code it's written in. 

It's shell (bash), which is interpreted at runtime like Python. You can see what languages make up a project on the right sidebar of a repository (expressed as percentages).

> The Steam Deck is my first chance to experiment with Linux and I find everything I've learned so far to be very fascinating. I'm also new to Github and find the site very cool as well.

Good. Welcome!

> I had a brief chance to try the testing branch and tested a couple different servers. *Worked perfectly during my brief testing*. 

Will test a bit more and migrate these changes to the Stable branch next week. We had a handful of hotfixes for various things this weekend.

> If there's anything else that comes up, I'll do my best to document it and let you know. 

Please! Testers are very much welcome. It's the only one to track down esoteric bugs and fix them for other users.

> I'll also be sure to spread the good word about your program, because I had to look around a little while before I found it (one person mentioned it on the DayZ page on Protondb). Thanks again!

I'm aware of this; discoverability currently is nil. The issue is that this grew out of DZTUI, which is the name of the repo, and originally I put DZGUI on its own branch inside of DZTUI while elaborating it. Technically, they both use the same underlying principles and share a config file format that can be moved from one to the other. Anyway, the consequence of this is that "DZGUI" is not getting indexed by search engines, so I need to split it off into its own repo eventually, but I wanted to flesh it out a bit more. I did see it mentioned a few times on PDB, and it always leaves me crestfallen to see a user bounce off of trying DayZ because they can't get things working or can't find the application, so discoverability would be good. I've mainly just been operating in stealth mode because there was some unstable stuff that needed ironing out before offering it to a wider audience.

I'll probably make a post about the latest stable release on Monday or Tuesday of next week, as it represents a decent milestone and has most of the features users were asking for now. I also want to get more testers onboard so that I can start trialing fully automatic installation of mods, which is something DZTUI already has, but needs to be implemented with more care in DZGUI due to the GUI-driven nature of it all and the need for user-friendliness versus DZTUI just expecting you to figure things out on your own.

**Comment by aclist** [comment]
This is now live on Stable (`2.5.0`).
