### ISSUE TITLE
[BUG] Fails to launch

### ISSUE THREAD

**Issue by bongjutsu** [aclist/dztui#38]
**Info**
DZGUI version: 2.7.0
Mode (normal/debug): Both
Server ID: 16716438
Linux distribution: Arch

**Bug description**
Since 2.7.0, the script will not launch any servers I have added via dztuirc

**Steps to reproduce the behavior:**
1. Launch server via quick favourites or added server list

**Expected behavior**
When running in debug mode the command seems to be correct, when running in regular mode the script will check the mod list and seemingly go through the procedure to launch the game, only to silently crash and have steam not do anything.

**Comment by fossean** [comment]
I have the same problem. Was working perfectly in the previous version.

DZGUI version: 2.7.0
Mode (normal/debug): Both
Server ID: 16716438
Linux distribution: MX Linux (Debian-base)

Bug description
Since 2.7.0, the script will not launch any servers 

Steps to reproduce the behavior:
1. Launch server via quick favourites or added server list

The debug gives this output: 

`This is a dry run.
These options would have been used to launch the game:

steam -applaunch 221100 -connect=51.210.155.18:2402 -nolaunc
her -nosplash -skipintro "-mod=@5553c1d7;@fc467aae;@6b8465ab
;@883ee43e;@7da32be2;@5beab442;@5dfd1352;@2b377610;@39246611
;@7da0e8b8;@7b81509f;@9d942188;@2202849b;@df13b7df;@74fd1cf2
;@94ae9cb7;@7595cfee;@f885a570;@8ac285b7;@ee547731;@d13c0257
;@dbd60dc6;@ba1c7058;@9dd22c91"`

Shouldn't the player name be passed to the launch options?

**Comment by aclist** [comment]
Thanks for the detailed descriptions, everyone. That made it easy to identify the issue and fix it.

> Shouldn't the player name be passed to the launch options?

Looks like the player name was being correctly passed on the live version, but it was missing from the printout in the debug output. Added that as well.

**Comment by bongjutsu** [comment]
Upon testing today issue seems to be resolved, closing
