### ISSUE TITLE
[BUG] Launcher buggs out when connecting to `82.208.17.115:27368`

### ISSUE THREAD

**Issue by jiriks74** [aclist/dztui#40]
**Info**
DZGUI version: 3.1.0-rc.15
Mode (normal/debug): Both
Server ID: 17593374
Linux distribution: Garuda (Arch)

**Bug description**
The launcher tries to download [PVEZ Reloaded mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2831742849&searchtext=pvez+reloaded) when it is already downloaded and subscribed.

I used [another tool](https://github.com/bastimeyer/dayz-linux-cli-launcher) to get the cli argument to connect to the server:

```bash
steam -applaunch 221100 -connect=82.208.17.115:27368 -nolauncher -nosplash -name=jiriks74 -skipintro "-mod=@Fl6QpQ;@gffIqA;@NYZ5pg;@-6dSmQ;@iv8hfg;@xBWfkQ;@EMvppg;@nL68ng;@FJrAiA;@7Iv_jQ;@o5Poig;@9p3Bqw;@JsZNkw;@d41tqw;@Uk8xcw;@g7hlgQ;@8Gd2iA;@Q5eTpg;@4nD7ZQ;@g01VXQ;@gffIqA;@AL3Lqg;@PxFcjw;@lyiphw;@kCc5XQ;@IJ62lw;@BLDvXA"
```

(The server changed hostings, so the ip was different on first run so I could move my character between the servers)

**Steps to reproduce the behavior:**
1. Open DZGUI
2. Add `17593374` server
3. Connect to it

**Expected behavior**
The launcher should run the game

**Comment by aclist** [comment]
You can use Debug Mode to perform a dry-run that will print the launch arguments that would be used to connect. It's in the Advanced Options menu.

I'll work on reproducing this.

**Comment by aclist** [comment]
OK, I see what you are talking about here. It doesn't get to the debug or connect output because it keeps getting stuck on that mod. I think I have an idea about what is causing this, but it also seems a bit obscure, so need some time to investigate.

**Comment by jiriks74** [comment]
> OK, I see what you are talking about here and was able to reproduce the bug. It doesn't get to the debug or connect output because it keeps getting stuck on that mod. I think I have an idea about what is causing this, but it also seems a bit obscure, so need some time to investigate.

Thanks and don't worry. As I have the command created from the other tool I can successfully connect to the server, so I don't need this ASAP.

Maybe add an option in the advanced setting that would allow you to `One time ignore unsuccessful mod instalation` or something like that. Could save someone when they want to play but the launcher bugs out even though everything's ok. Add a warning or something that people know it's probably not the best thing to do and I think that it could be ok. It took me some time to get the command so I could play with friends and this could be really helpful in those situations.

**Comment by aclist** [comment]
This is fixed, please test. 

Seems some servers were returning multiples of the same mod in their modlist instead of pre-sanitizing them to a list of unique IDs. We were interpreting that as a new mod that was missing locally. This is technically the fault of the server operator for including extra garbge in their modlist.

I think it's better to noisily fail and prevent connection in the event of bugs like this, since it increases the possibility of the end-user reporting the issue and it getting patched. If we just let the user skip annoyances and brute force it until they get the desired outcome, it would prevent finding the root cause. 99% of people don't report bugs.  Bugs should be blockers and prevent you from playing. It may seem annoying, but it's better than kicking the can down the curb and obscuring the problem with some workarounds.

**Comment by jiriks74** [comment]
Wouldn't something like: please report the bug, but you can "try to connect" help?


Add a link to open a new issue, maybe with some template text to put into the issue like versions and the server id/ip - make it easy to report the issue and allow them to "try to run the game" after that. I'll look if there's a way to automatically create GitHub issues (after user consents to do so) - I'd be ok trying out servers that would appear in issues and report wether there's actually a problem for me or there's nothing.

Just brainstorming here. I think that it could be done in a way that would be the best of both cases.

**Comment by aclist** [comment]
The thing is that the only time users report bugs is when the application critically fails and stops working. You can't incentivize it any other way. The only time they report them is when they have a problem, they come here, report it, and then when it is fixed and as soon as they can play again, they stop communicating. You're in the 0.0001% of users who actually file proper bug reports. If I put an escape hatch in the application, no one will ever report anything, I guarantee it.

In order to be fully aware of blocking issues, it's best to disincentive skipping them. It sounds good on paper to have this Swiss Army Knife, but judging from the last year of bug reports, nothing you can do will persuade people to report an issue unless they are an outlier/power user or if everything breaks.

The pool of possible edge cases continues to grow smaller as we learn about the specific scenarios certain servers have.

We actually do have templates for issue creation, like the one you used above, where you choose from either the Bug or Feature button. You still need an account to create issues, so adding programmatic API support inside of the application would be challenging both from an authentication issue, and also from a pure GUI issue, due to the limitations of the library used to draw menus. There are certain things we simply "can't do" from an engineering perspective inside of the application due to the barebones GUI library being used, which was chosen because it's one of the few that works OOTB on Steam Deck without leveraging a more featureful API like Qt.

Were you able to test and confirm that the above is fixed?

**Comment by aclist** [comment]
-- Pushed this hotfix to the mainline branch as well outside of the usual release cadence

**Comment by jiriks74** [comment]
I think I understand your point. Thanks for taking some time to explain it to me, I really appreciate it.

As for testing the patch out. I am not currently at my pc. It's at my college dorm, and I'm at home, so I'll be able to test it out on Sunday. But I'll try to get to another pc. I have a fladhdisk and an external SSD which I have DayZ on so if I get to some pc that can run it, I'll try to.

**Comment by jiriks74** [comment]
Ok so for thé other PC the launcher looks like it does work. I haven't been able to connets to the server yet, because I'm running on an external HDD as of now, but the launcher downloaded all the mods and launched the game.
