### ISSUE TITLE
[BUG] "Steam must be running on the current desktop to use this feature."

### ISSUE THREAD

**Issue by tarkkanakki** [aclist/dztui#43]
**Info**
DZGUI version: 3.1.2-3.1.3
Mode (normal/debug): Normal
Server ID:
Linux distribution: Arch, Gentoo

**Bug description**
Script refuses to to pass "is_steam_running" check on dwm, making it broken.

**Steps to reproduce the behavior:**
1. Launch  script
2. Pick server
3. Try to connect to any server
5. See error (Steam must be running on the current desktop to use this feature.)

**Expected behavior**
The check doesn't pass on my system, or on friends systems, needing to edit the script to comment out line 582 (on version 3.1.2).

**Comment by Irets** [comment]
Can confirm.

Users of fully fletched desktop environments _probably_ don't have issues but this implementation of the "is steam running" check will fail at least on dwm.

**Comment by fossean** [comment]
DZGUI version: 3.1.3
Mode (normal/debug): Normal
Server ID:
Linux distribution: MX-Linux (debian)

Bug description
Script refuses to to pass "is_steam_running" check when forcing mod updates

I deleted line 582 but problem persisted. Searched script for "Steam must be running" and deleted second line, problem seems to be resolved.

**Comment by aclist** [comment]
@tarkkanakki 

Thanks for the initial report.

@Irets 

> Users of fully fletched desktop environments _probably_ don't have issues but this implementation of the "is steam running" check will fail at least on dwm. This is on dzgui 3.1.3

I am thinking about what to do here. I actually use i3wm for my main WM but run games on a separate TTY with icewm and xorg.conf mapping one discrete display to a single X screen so that Nvidia G-Sync works as intended, and to avoid problems I had observed in the past with tiling window managers and games expecting floating windows, so I failed to take stock of this issue when using the "games TTY" environment. 

This change was originally introduced because a KDE user reported that it was raising the wrong window for input. I had a fleeting thought in my mind that enforcing the desktop check would introduce problems on workspace-driven desktops, but was also concerned about changes to the automated mod installation trying to raise the Steam window and failing to find it.

This logic chiefly affects automod installation and should not block the user from standard use of the tool. So for starters, I will move this logic so that it only touches the automod process.

Secondly, I don't want to hardcode specific Steam client discovery on a per-WM basis, as that could get unmaintainable fast, so I will experiment with raising the window but not enforcing the desktop check per se. The problem is that the Steam client generates quite a lot of PIDs all named "Steam" that may or may not point to the "actual" Steam client we want to raise.

@fossean 
> I deleted line 582 but problem persisted. Searched script for "Steam must be running" and deleted second line, problem seems to be resolved.

In your case, since you enabled automod installation and chose to force update mods, you would need to uncomment lines 582 and 1111.

Proposed hotfix:

I will drop the desktop check for now, since it should still ensure coverage on both workspace-driven WMs and floating/desktop WMs, with the caveat that it may affect granular ability to find and target the Steam window in the latter case.

I will keep this stub open while testing ways of reliably raising the Steam window across desktop/WM environments.

**Comment by aclist** [comment]
1. Copy the below to a file `target_window.sh`
2. `chmod +x target_window.sh`
3. Place Steam client on a separate workspace than the main workspace
4. From the main workspace, invoke `./target_window.sh`

Expectation:

- Steam window is captured and focused on the current workspace
- Steam console opens
- "TEXTAREA INPUT TEST" is typed in the focused field
- The typed text is selected and deleted
- The Steam client is reverted to the minigameslist
- Script exits and the Steam client remains on the current workspace

```
#!/bin/bash
wid=$(xdotool search --onlyvisible --name "Steam")
steam steam://open/console
sleep 2s
xdotool windowraise $wid
xdotool type --delay 20 "TEXTAREA INPUT TEST"
sleep 0.5s
xdotool key Ctrl+a
sleep 0.5s
xdotool key Delete
steam steam://open/minigameslist

```

**Comment by aclist** [comment]
Hello, testing complete. Read this carefully if you are a dwm user, since it pertains to you specifically. 

> Users of fully fletched desktop environments _probably_ don't have issues but this implementation of the "is steam running" check will fail at least on dwm. This is on dzgui 3.1.3

In answer to your question, the word "desktop" here is a bit misleading. This is not because dwm lacks a "desktop," while full desktop environments (DEs) do. It is because dwm does not report the `_NET_CURRENT_DESKTOP` value when polled by other applications. This does not refer literally to a desktop as the end user conceives of it, but to a virtual space on the window/tag stack drawn by the display server. Most other tiling window managers without DEs do support this value.

As you know, dwm by design ships with the minimum required featureset for basic functionality and expects the user to patch in other features supported by more feature complete window managers. In this case, the required patch would be this: https://dwm.suckless.org/patches/current_desktop/

However, after some review, I have found that we can omit the requirement of Steam being on the literal current desktop, as finding and activating the window regardless of its location seems to work reliably regardless (probably; the xdotool bug is still open). So you do not need the above patch. (You do need the one described below.)

To reiterate the post from the other day, the new logic will be as follows:

Case 1. If the user is using the standard mode (manual mod installation), we will simply poll the Steam window and load the workshop links in the foreground. This process waits for manual input by the user (click to Subscribe to a mod), so it is OK if the window is activated in the background. If Steam is not even running, it will launch first and then open to the given Workshop page. (Note: prefer running Steam before DZGUI)

Note: On dwm, this is going to lead to the DZGUI Watcher notifying you about mods being spawned on the current workspace, while Steam could be inside any other tag in the stack. Preferably, you should be using Steam in the same workspace if you want the DZGUI dialog and Steam Workshop to appear next to each other. This only happens on dwm because of the way it sets the urgency bit on certain tags. (See additional notes below regarding patching the `_NET_ACTIVE_WINDOW` response.) However, it does not block any functionality per se.

Case 2. This is the important case. If the user has enabled automod installation, DZGUI must activate (raise and focus) the Steam client and interact with the dev console to issue mod download commands. The new logic will largely do what it did before, with some refinements:

- Look for the existence of the Steam process
- If its PID cannot be found, warn and return without running automod installation; revert to manual mod installation
- If the Steam process was found, attempt to activate (raise and focus) the Steam client to issue mod download commands.
- Issue commands into the window id of the Steam process to trigger downloads. (This is a protective change, as it supports sending commands into the window in the background even if the user is on dwm and declines to patch their build as described below. That is by far the rarest use case, but conservatively supporting it.)

*Note: the more desirable outcome here is issuing the commands while the window is physically visible, so that you can see the commands being issued. If your WM does not respond to `_NET_ACTIVE_WINDOW` requests in a permissive manner, it will lead to input automation (download commands) being sent to the Steam client in the background without a visual indication of progress. 

dwm does not respond to windowactivate requests in the normal manner, using the more stricter response of setting the urgency bit of the tag and alerting you that you have an active program in that tag by highlighting the number in the tag stack. It requires the user to manually switch to that tag; it does not actually switch to that program and foreground it OOTB. To do so, you must apply this patch: https://dwm.suckless.org/patches/focusonnetactive/

If you intend to use automod installation and dwm, you MUST apply this patch if you want to see the progress of download commands. Otherwise, if your workflow involves opening DZGUI in a separate tag than the one Steam is in, you may have to wait an unspecified amount of time (could be a long time for dozens of mods) until this finishes. If you are okay with that, that is fine, too.

*Note 2: Theoretically, we could draw the DZGUI Watcher here again to update on the progress of these download commands, but this would solely be for the purpose of supporting the dwm edge case where: 

1. DZGUI and Steam are in separate tags
2. The user has enabled automod installation
3. The user hasn't applied the corresponding patches to their dwm build
4. The user wants to remain on a different tag and get progress updates on Steam from another tag

This is a very small surface for a use case, so DZGUI must not support esoteric workarounds or drop functionality that provides failsafes for other window managers in order to support unpatched dwm builds that do not respond to `_NET_ACTIVE_WINDOW` messages as described above. 

Meanwhile, I will consider foregrounding the DZGUI Watcher as a general convenience function for all environments (e.g., report via a dialog how many mods have currently been staged for download while the more opaque download commands are issued into the Steam client: "Requesting download for mod 1/30").

The hotfix the other day was to restore barebones functionality, but it is not a good longterm solution since it will affect other users. If you are using dwm and the case above (items 1-4) affects you, it is your responsibility to apply the requisite patches. dwm is designed to be recompiled in an ad-hoc fashion by the user. A link to the patch will also be added to the DZGUI dialog window triggered when a user first enables automod installation, and to the documentation.

Secondly, if you are not using automod installation but still want the freedom to open Steam on an arbitrary tag and DZGUI on a separate tag and have Steam physically pop open when opening Workshop mods, you should also apply the above patch. Again, preferably, you should open Steam and DZGUI in the same workspace for the least jarring experience, but this is subjective.

I do not recommend simply deleting or uncommenting lines of code as a permanent or sustainable workaround, as the goal of the application is not merely to launch DayZ and be done with it, but to do so in a hopefully sane manner that accounts for and hedges against possible problems, albeit ones on environments other than your own, or ones that only surface when specific options are enabled.

These changes will go live on both branches effective the time this ticket is closed. This is a grace period to update your environment before the change.

**Comment by aclist** [comment]
This change is now live. DZGUI should raise and target the Steam client window correctly on most major window managers, including i3 and dwm. As mentioned above, if you are using multiple workspaces on dwm and have not patched to bring active windows to the front, it may or not function correctly.

Steam client discovery will not work on certain legacy window managers like icewm if the Steam window is on a completely different screen.
