### ISSUE TITLE
[BUG] key press seems to be held down while entering commands in steam workshop 

### ISSUE THREAD

**Issue by vincent1190** [aclist/dztui#48]
![PXL_20230106_183658148](https://user-images.githubusercontent.com/18622363/211077073-ace30268-f3e8-430c-bb9b-d45c332973e8.jpg)
**Info**
DZGUI version: 3.6.1
Mode (normal/debug): normal
Server ID:
Linux distribution: steamos (steam deck)

**Bug description**
While commands being entered into steam workshop, it seems the w key is held down. This results in incorrect commands being sent to steam workshop and inability to update mods

**Steps to reproduce the behavior:**
Force update local mods or select server which have mods that are out of date

**Comment by aclist** [comment]
I'm aware of this issue and have been trying to find a fix for it for weeks, since it affects some other projects. It appears to be a bug in xdotool itself with the way it handles the repeat rate of key entry. Even specifying slower input with the `--delay` flag does not help. It's not the w key necessarily; it could be any intermittent key.

The issue seems to be particularly present if the user has set a fast repeat rate (e.g. `xset r rate 400 90`). However, even if we temporarily slow down the repeat rate and then revert it to the user's settings, this issue still happens, so I am inclined to believe it is an xdotool problem, and I have seen a few reports here and there about it.

I do have a fix, but I was holding it back for a bit because I wasn't sure if this issue was affecting other users and because it introduces a new dependency.

Essentially, instead of typing the command verbatim, we can copy it to the system clipboard and then insert it with a simulated paste motion. This ensures that the input is only a single keypress (Ctrl+v), rather than a series of keystrokes, which seems to be what triggers this bug.

I need to take a day to verify whether the dependency I want to add is included on the Deck out of the box, but this fix should otherwise work.

**Comment by vincent1190** [comment]
Oh that sounds perfect and as for the dependency I want to say the steam deck is ready only but maybe it can be downloaded via a flatpack?

**Comment by aclist** [comment]
Yes, I've tried to keep as few dependencies as possible and only use ones found OOTB on Steam Deck, so that functionality will always work on both SD and desktop versions without the need for extraneous tools. Luckily, SD ships with some extra tools pre-installed that have generally been all we need. I'd rather not require installing additional tools on SD, as it greatly complicates it for inexperienced users and stops being a turnkey solution. I don't mind requiring desktop users to do some setup, as they won't be on a monolithic system.

Anyway, I just looked through the SD and unfortunately, it doesn't have any of the three clipboard tools I was hoping to use. As an alternative, I'm going to push a hotfix that changes the way the text input is invoked a bit, and let's see if that helps.

I'll push the hotfix in five minutes or so and reference it here.

**Comment by aclist** [comment]
OK, try now with version `3.1.7`. It seems improved over here and I wasn't getting the "held down key" side effect.

**Comment by vincent1190** [comment]
Looks like it worked!!! In the Sunnyvale server now after running forced local mods update and it automatically updating the Sunnyvale mod list itself when I ran there deer isle server

**Comment by aclist** [comment]
OK, good. Will keep monitoring this to see if it recurs. Feel free to reopen the issue. Out of curiosity, what made you choose to enable auto mod installation? Just having to manually subscribe to so many mods was tedious? I'm just asking to get a better sense of what percentage of users are using manual vs. automatic. I think most users use manual or haven't found the automatic mode in the menu yet.

**Comment by vincent1190** [comment]
I don't recall setting it. I might have just went in and did it but I don't recall. I remember thinking that I wanted my brain to be as shut off as possible during this process which is why I went with the automatic install option. I want to say that the mod list was set up to automatically update by default and even if it wasn't I would look to set it since yes it is a lot of mods for the server I was using and it would indeed be too tedious for me to monitor over all of them. Thank you for working this cause I would have had my money wasted on the game otherwise

**Comment by aclist** [comment]
OK, thanks for the info. Feel free to reach out again in the future.
