### ISSUE TITLE
[BUG] Error 97 Failed to fetch modlist

### ISSUE THREAD

**Issue by Squawwkk** [aclist/dztui#50]
**Info**
DZGUI version: 3.1.7
Mode (normal/debug): both
Server ID: 18098930
Linux distribution: Arch

**Bug description**
When attemping to join any server from My servers it fails with error 97.

**Log**
Linux: Linux 6.1.4-arch1-1 x86_64
Version: 3.1.7
Branch: stable
Whitelist: 13898220,12159107,4859769,13196778,18098930,18098930,18098930,18098930
Steam path: /home/max/.local/share/Steam
Workshop path: /home/max/.local/share/Steam/steamapps/workshop/content/221100
Game path: /home/max/.local/share/Steam/steamapps/common/DayZ

Mods:
1966_Ford_Mustang	@1971972993-1966_Ford_Mustang
1SKGaming	@2813848182-1SKGaming
1SKGamingModPack1	@2085377668-1SKGamingModPack1
Admirals Diving Mod	@2709289485-Admirals_Diving_Mod
Advanced Weapon Scopes	@2143128974-Advanced_Weapon_ScopesKernel 6.1.4-arch1-1
Airdrop-Upgraded	@1870524790-Airdrop_Upgraded
ArmA 2 ACR Weapon Pack	@2141780688-ArmA_2_ACR_Weapon_Pack
Arma 2 Helicopters Remastered	@2651195301-Arma_2_Helicopters_Remastered
ArmA 2 Props Pack	@2160294330-ArmA_2_Props_Pack
AwesomeArmbands	@1780852482-AwesomeArmbands
Banking	@1836257061-Banking
BaseBuildingPlus	@1710977250-BaseBuildingPlus
BodyRemoval	@2425071577-BodyRemoval
Breachingcharge	@1827241477-Breachingcharge
BuildAnywhere_v3	@1854626456-BuildAnywhere_v3
BuilderItems	@1565871491-BuilderItems
BuildingsMegaModPack	@2307297070-BuildingsMegaModPack
BuildingsModPack7	@2762521201-BuildingsModPack7
CannabisPlus	@1932611410-CannabisPlus
CarCover	@2303483532-CarCover
CF	@1559212036-CF
ChernarusRP AE86	@2064965521-ChernarusRP_AE86
Cheytac M200 from ArmA 2 Port	@1819921337-Cheytac_M200_from_ArmA_2_Port
CJ187-LootChest	@2345073965-CJ187_LootChest
CJ187-SummerChernarus	@1644467354-CJ187_Summer_Chernarus
Cl0ud's Military Gear	@1630943713-Cl0ud_s_Military_Gear
Code Lock	@1646187754-Code_Lock
Collectable Items	@2575183443-Collectable_Items
Community-Online-Tools	@1564026768-Community_Online_Tools
Crocos Quadbike	@2757080411-Croco_s_Quadbike
[CrSk] VAZ-2107	@1818957231-CrSk_VAZ_2107
Custom Barrels by kaetzchen	@1966481101-Custom_Barrels_by_kaetzchen
Dabs Framework	@2545327648-Dabs_Framework
DayZCasinoV2	@1940425039-DayZCasinoV2
DayZ Editor Loader	@2276010135-DayZ_Editor_Loader
DayZ-Expansion	@2116151222-DayZ_Expansion
DayZ-Expansion-AI	@2792982069-DayZ_Expansion_AI
DayZ-Expansion-Animations	@2793893086-DayZ_Expansion_Animations
DayZ-Expansion-Core	@2291785308-DayZ_Expansion_Core
DayZ-Expansion-Licensed	@2116157322-DayZ_Expansion_Licensed
DayZ-Expansion-Market	@2572328470-DayZ_Expansion_Market
DayZ-Expansion-Missions	@2792984177-DayZ_Expansion_Missions
DayZ-Expansion-Name-Tags	@2576460232-DayZ_Expansion_Name_Tags
DayZ-Expansion-Vehicles	@2291785437-DayZ_Expansion_Vehicles
DDU Vanilla Enhanced	@1758789549-DDU_Vanilla_Enhanced
DDUVanillaEnhanced	@2310070450-DDUVanillaEnhanced
DisableGardenPlots	@1719445243-DisableGardenPlots
Dmns_ExtraWeaponZ	@1721821008-Dmns_ExtraWeaponZ
DNA Keycards	@2714183642-DNA_Keycards
Dogtags	@2303554682-Dogtags
Ear-Plugs	@1819514788-Ear_Plugs
FlipTransport	@1832448183-FlipTransport
Gerphelius Zil-130	@1826872082-Gerphelius_Zil_130
GoreZ	@1648967877-GoreZ
Helicrash Licensed	@2491484149-Helicrash_Licensed
IndustrialModPack	@2358569462-IndustrialModPack
Inventory Move Sounds	@2444247391-Inventory_Move_Sounds
IRP-Land-Rover-Defender-110	@1912237302-IRP_Land_Rover_Defender_110
Lightsword	@1964490092-Lightsword
Mag Obfuscation	@2449234595-Mag_Obfuscation
Mass'sManyItemOverhaul	@1566911166-Mass_sManyItemOverhaul
Modular Vest System	@1962144102-Modular_Vest_System
MoreGuns	@1665663702-MoreGuns
Mortys Weapons	@2155726353-Mortys_Weapons
MosinScope	@1579016654-MosinScope
MuchCarKey	@2049002856-MuchCarKey
MuchDecos	@1967655509-MuchDecos
MuchStuffPack	@1991570984-MuchStuffPack
MunghardsItempack	@1734713776-MunghardsItempack
Notes	@1999076953-Notes
OP_BaseItems	@1617874376-OP_BaseItems
P2PTrader (Player to Player Trader)	@2012299152-P2PTrader_Player_to_Player_Trader
Pipsi_Net_SkinPack	@1768789249-Pipsi_Net_SkinPack
Rearmed Server Pack	@2490100317-Rearmed_Server_Pack
RedFalcon Flight System Heliz	@2692979668-RedFalcon_Flight_System_Heliz
Reduce Vehicle Damage	@2117984167-Reduce_Vehicle_Damage
[Remastered] Arma Weapon Pack	@1793351435-Remastered_Arma_Weapon_Pack
Saline Bag+	@1736675168-Saline_Bag
SchanaModGlobalChat	@2115602332-SchanaModGlobalChat
SchanaModParty	@2075831381-SchanaModParty
ShakeForFruit	@2166325582-ShakeForFruit
shd_Retextures	@2623577702-shd_Retextures
SIX-DayZ-Auto-Run	@1781132597-SIX_DayZ_Auto_Run
Snap Heli To HeliPad	@2175630271-Snap_Heli_To_HeliPad
SPBuilding	@2177232791-SPBuilding
Specialist Weapon Pack	@1945945241-Specialist_Weapon_Pack
Survivalists_FacePaints	@2786677604-Survivalists_FacePaints
Tactical Flava	@2646817942-Tactical_Flava
TEPBillboardSigns	@1676585852-TEPBillboardSigns
TerrainIslands	@2393499239-TerrainIslands
ToxicZone	@1752669393-ToxicZone
Trader	@1590841260-Trader
Trolley Kart	@2221274779-Trolley_Kart
Unlimited Stamina	@1560819773-Unlimited_Stamina
VanillaPlusPlusMap	@1623711988-VanillaPlusPlusMap
VPPAdminTools	@1828439124-VPPAdminTools
VPPNotifications	@1680673106-VPPNotifications
WeaponReduxPack	@1559317235-WeaponReduxPack
WindstridesClothingPack	@1797720064-WindstridesClothingPack
Winter Chernarus	@1597140327-Winter_Chernarus
zSpawnSelection	@2017605880-zSpawnSelection
ZStuff	@2384407442-ZStuff

**Comment by aclist** [comment]
Thanks for the report. I'll try to explain what is happening here.

We only use the BM API anymore to get metadata when users "add server by ID." It's merely there as a convenience function so that users can quickly store and look up servers by ID rather than IP. 

When storing by ID, we fetch the metadata from BM and find the IP and port they report the server is on. Because single servers can actually be running multiple maps or game modes behind different ports (BM doesn't report this), we then query the master indexing server to expose which maps are actually running at this IP. Then we select the one at the port originally stated by BM.

The problem is that BM's data here is stale, and is reporting that this server is on port 2302, when in fact it is on port 2602. Being unable to find the asked-for game at port 2302, the process exits.

If you instead choose to "Connect by IP," it will fetch all of the maps on different ports behind that IP and show them to you as a list. You can then select the desired one and it will work for this server. (Tested and confirmed)

I would like to drop the BM API altogether, as we barely use it anymore, and it is only being kept around (as mentioned above) for the purposes of aligning IDs with servers. I would prefer to have users create their favorites list using IPs, and change the config file to looking something like this:

```
whitelist="
         100.100.100.100
         200.200.200.200
         "
```

IPs are a bit longer than IDs, so better to store on a linewise basis. So we'd have to refactor how we parse the whitelist a bit.

The problem I see is that if we switch to add-server-by-IP instead of add-server-by-ID, we need to let users carrying these old server IDs migrate them to IPs without having to manually look up each one. It would be simple enough to just query them all and then store the resulting IPs, but since the old IDs correspond to specific IP:PORT combinations, and since (per this bug report) we can't be sure if BM's data is trustworthy anymore, I'm not sure how to proceed on that without asking users to manually rebuild their favorites list using IPs and selecting the right maps from the list that comes back. (The majority of servers just have one port, but since some have multiple, I have to assume this would be necessary at some point.)

I guess this can be semi-automated by fetching what we can, converting to IPs, and then asking users to select the right ports from the list for any servers with multiple maps, then storing the new "favorite IP and port list" and discarding the legacy IDs.

I've been reluctant to do the above because it seems to mostly be working in 99% of cases and because it breaks backwards functionality. This is basically tech-debt at this point, and it should be done, just needs to be done with care and clarified to users so they know what to expect.

**Comment by Squawwkk** [comment]
Thank you for your reply and through connect through IP we're in.
Thanks for your work boss.

**Comment by aclist** [comment]
OK, good. I'll probably reopen this in some form or another and patch this eventually.
