### ISSUE TITLE
[BUG] Spamming w in the steam console, DZGUI always forces focus

### ISSUE THREAD

**Issue by jiriks74** [aclist/dztui#51]
**Info**
DZGUI version: 3.2.0-rc1
Mode (normal/debug): normal
Server ID: 16366316
Linux distribution: Archlinux

**Bug description**
The automod install types in bad commands:
```
wwwwwwwworkshwop_dowwnloawd_itemw 2211w00 26w23995w836wwwww
```

**Steps to reproduce the behavior:**
1. Connect to a server that requires a mod to be installed
2. Connect to it
3. Click ok in the dialogue that appears
4. See the messed up steam console commands
5. Have hard time closing the DZGUI watcher that repeatedly forces focus

**Expected behavior**
Normal `workshop_download_item` commands

Suggestion for the forced focus: Make it show above others. This makes sure that it doesn't disappear on the steamdeck while allowing people to kill it when it goes rogue.

<details>

<summary>Terminal output</summary>

```bash
[DZGUI] Checking response time of servers
steam.sh[104149]: Running Steam on garuda Soaring 64-bit
steam.sh[104149]: STEAM_RUNTIME is enabled automatically
setup.sh[104223]: Steam runtime environment up-to-date!
steam.sh[104149]: Steam client's requirements are satisfied
There are no windows in the stack
Invalid window '%1'
Usage: windowactivate [options] [window=%1]
--sync    - only exit once the window is active (is visible + active)
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
There are no windows in the stack
Invalid window '%1'
Usage: windowactivate [options] [window=%1]
--sync    - only exit once the window is active (is visible + active)
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
There are no windows in the stack
Invalid window '%1'
Usage: windowactivate [options] [window=%1]
--sync    - only exit once the window is active (is visible + active)
If no window is given, %1 is used. See WINDOW STACK in xdotool(1)
```

</details>

**Comment by aclist** [comment]
Thanks for the report. The spam is related to a bug in xdotool that causes the key repeat rate to go wild. The terminal output is a false positive here. It does relate to the xdotool bug, but it will still write this warning even when the window is targeted correctly.

This is fixed on the stable branch, can you try there? I need to backport this fix to the testing branch.

Regarding the forced popup, yes, I've been thinking about making it less aggressive (not continually forcing it to the foreground) while still having some way of putting it at the top of the stack. This is a bit tricky, so need to test more.

**Comment by aclist** [comment]
I changed the behavior of the progress window and pushed a new version. I also found a couple other obscure bugs:

1. Mods needing update not breaking on newline and consequently not getting appended to download list correctly (fixed in the above update)
2. Rare case where mods staged for download get dropped from the download request (investigating, but seems straightforward to fix)

All of the above applies to the Stable branch.

**Comment by jiriks74** [comment]
Thanks for the fixes!

To the forced focus:
I reinstalled my system (the SSD I used before died, so that's why I was not replying for a long time, sorry for that) and I used the install script after this report. Then I forgot about this issue and launched the game through is and as it outputed gibberish into the steam console it was waiting for the mods that would never download. And as I didn't run it from a terminal I couldn't do anything fast enough to kill it and I had to result to switching to tty and running `killall dzgui.sh` from there as there was no chance I'd do it from the GUI.

If you'd like to keep the aggressive forced focus, maybe adding a cancel button wouldn't be bad. Also option for turning it off would be nice, in that case, as people on PC would be doing other things when steam would be downloading eg. 76GB of map data.

I'll switch to the stable branch and report on whether it works. Is there a way I can delete the downloaded mods so that I could trigger the download again?

Thx for your amazing work!

**Comment by aclist** [comment]
> To the forced focus:
I reinstalled my system (the SSD I used before died, so that's why I was not replying for a long time, sorry for that) and I used the install script after this report. Then I forgot about this issue and launched the game through is and as it outputed gibberish into the steam console it was waiting for the mods that would never download. And as I didn't run it from a terminal I couldn't do anything fast enough to kill it and I had to result to switching to tty and running killall dzgui.sh from there as there was no chance I'd do it from the GUI.

Yeah, it was definitely ugly, and had happened to me a few times during testing, but I wasn't sure how widespread the scope was or if it was possible for this to happen in a "real-world" scenario.

> If you'd like to keep the aggressive forced focus, maybe adding a cancel button wouldn't be bad. Also option for turning it off would be nice, in that case, as people on PC would be doing other things when steam would be downloading eg. 76GB of map data.

Actually, it's possible to cancel that progress dialog by hitting ESC. I had hidden the cancel button because I thought users should be encouraged to allow the downloads to complete, as quitting prematurely is going to be bad. And I agree, it shouldn't block other processes if you want to do stuff in the same session. Overall, I think this was a bad design decision on my part.

I've opted to just raise the progress bar once as a reminder, and if the user wants to just watch the progress they can. Otherwise, they can just switch contexts using their window manager and the progress bar will go in the background (and can be accessed using whatever task manager/alt-tab/hotkey/process list they prefer to use).

> I'll switch to the stable branch and report on whether it works. Is there a way I can delete the downloaded mods so that I could trigger the download again?

You should be able to use the "Force update local mods" option from the Advanced Options menu if you have automods set to on. But there might still be some buggy behavior in there (still investigating).

Alternatively, if you open "List installed mods" from the main menu, it lists the path where all mods are saved and you can remove that.

**Comment by aclist** [comment]
Found some peculiar stuff about the way mod subscriptions are handled, will update this ticket later

**Comment by aclist** [comment]
Findings: I rm -rf'ed the mods directory in order to force trigger download of mods again. This worked, but I noticed that at some point Steam reported that the DayZ installation was missing files and had an integrity issue. I forced an update by selecting to verify integrity of local files via the right-click options menu. This triggered a download of 100GB of mods. (200+ mods) 

However, my understanding was that when auto downloading mods, we request them directly and they don't get "subscribed" to in the workshop. Indeed, checking the subscribed mods does not list any of these mods that were auto downloaded as being "subscribed to" by the account. Yet if the DayZ installation is force updated, it seems to revert to fetching these mods. Is Steam internally storing subscriptions some other way? If so, can we expect it to queue updates to mods even if they aren't visibly subscribed to?

**Comment by jiriks74** [comment]
I sadly do t have answers for that. Maybe contact steam support? With how they're pushing Linux these days I think they'll be happy to help out.

But as far as I know, when there was a server reset and a mod was updated, stream didn't download the update automatically, the launched had to do it. 

But that was like 2 months ago, so I'm not really sure.

But the behavior is weird indeed.

**Comment by aclist** [comment]
Well, Valve provides its APIs and tools on a very much as-is basis, so it can be difficult to get a reply on such matters unless the issue visibly affects a large number of users, such as a bug on the Steam client.

Anyway, I don't think this is overtly causing problems for now, so I am closing this issue. Feel free to open more issues in the future should you encounter something.
