### ISSUE TITLE
[BUG] Error 97 when trying to connect to server, won't save steam api key, error 96 when trying to connect via IP

### ISSUE THREAD

**Issue by bongjutsu** [aclist/dztui#58]
Sorry for the lengthy title, but I've got a nice trifecta of issues:

1.  When trying to connect to the server through the server list, I get error 97.
2.  When trying to add my steam API key via the dialogs, it doesn't actually get saved into dztuirc
3.  When manually adding a steamkey/steamapi entry into dztuirc, it seems to be ignored
4.  In a similar issue the suggested fix was to try connecting via IP, this fails with error 96
5.  Despite all of the above, if I set a server as favourite and quick connect, it launches

**Comment by bongjutsu** [comment]
For reference, the server I'm trying to connect to is:

https://www.battlemetrics.com/servers/dayz/18486238

**Comment by aclist** [comment]
Hmm, if you can't add your API key, that is almost surely the cause of not being able to connect to servers etc., since the server browser depends on that API. 

Trying to isolate the issue: 

There should be two scenarios where you would be prompted to enter the key:

1. First-time setup (no dztuirc present)
2. Triggering a specific menu option with no API key  (dztuirc present, but incomplete)

I tested both of these but was unable to reproduce it. Are you getting some kind of error message after selecting the server browser and inputting your API key? Does it just silently succeed? 

Can you try renaming dztuirc to a backup file and then trying the first-time setup with no dztuirc present? It sounds like you are carrying over a fairly oldish config file if there was no `steam_api` entry even present. (It should get auto-populated when updating to a new version and be left blank until first use.) New config entries are always seeded into the config file when there is a version update.

Connect by IP also depends on Steam API key, so it will not work without it. Quick connect uses the older BM server ID method.

All dialogs pertaining to API keys will test the key to make sure it is valid, so it shouldn't be possible at this point to enter an invalid key. Also check the permissions on your config file to see if it is writable.

Is this the first time you attempt to use the server browser? I am wondering why this would have surface recently, as there have been no changes to any part of that code.

**Comment by bongjutsu** [comment]
My dztuirc was definitely old, I'm a long time user. I'm surprised that it wasn't able to write the steam key into dztuirc, it went through the process of backing up the file after adding the key through the dialogs but it never seemed to actually save it. Going through the initial setup stage again and adding my keys again worked, however. I guess I'll close this one then

**Comment by aclist** [comment]
Yes, of course I recognize you as one of my most consistent bug reporters. Thank you!

My surmises is that the key itself (steam_api) was not present, so it had nowhere to place the value (the API numbers) into, but this is a vanishingly rare scenario, since as I said, any update of the application itself should always trigger writing placeholder keys into the config file whenever a new one is added, precisely for this purpose.

I looked through the function that is responsible for merging new changes into the config file, and it looks clean, but there may be some side effect I am overlooking here, so will test it later.

**Comment by aclist** [comment]
@bongjutsu Would you mind taking a look at ticket #59 and seeing if it is fixed? It doesn't apply to you, but it was reported by other people, and no one has replied to confirm after the bugfix. I'm waiting to release it into Stable until someone confirms this hotfix is working.
