### ISSUE TITLE
sysctl: command not found

### ISSUE THREAD

**Issue by thafluu** [aclist/dztui#61]
Thank you for the great launcher!

When installed the launcher I got 'line 1727: sysctl command not found' on launch. I solved this by adding a 'sudo' infront of the sysctl command in that line, as I need sudo to run sysctl on my system. This might be OS-specific, I'm on openSUSE Tumbleweed. I just wanted to open this issue in case others have the same problem :)

**Comment by aclist** [comment]
Thanks for pointing that out, simple oversight on my part. I've pushed a hotfix into all branches.

**Comment by aclist** [comment]
I'm reopening this because I need to reevaluate the ramifications of sudo escalation for users launching DZGUI through a shortcut, such as inside of the Steam library, rather than the terminal. This may block the ability to launch the program altogether. 

While there are ways of determining whether we launched from Steam or a terminal, due to the variability of how distros might implement sysctl, I am leaning towards dropping the map count check at boot and just leaving it as an admonition to the user in the documentation. Alternatively, we could just pop up the warning dialog and exit the application until they set the map count themselves. As a final possibility, we could check whether the map count can even be polled without sudo escalation and, if not, bring up a dialog prompting for the password.

**Comment by aclist** [comment]
New, simpler solution:

- If a config file is missing, always interpolate the sudo password through dialogs regardless of whether invoked from the terminal or a launcher. 
- Use the sudo password to check the sysctl vm map count one time. 
- If it is smaller than the required limit, write a conf file upping the limit and load it, then boot DZGUI. 
- If it meets or exceeds the limit, write the current vm map count value to a conf file as a placeholder and then boot DZGUI
- On subsequent invocations, never ask the user again provided the conf file is present

Starting with version `3.2.7`, you'll be asked for the sudo password once in order to validate this check, but then it won't happen again.
