### ISSUE TITLE
wmctrl or xdotool issue

### ISSUE THREAD

**Issue by santony14111** [aclist/dztui#67]
can someone please Help me? i had DZGUI installed on my Steamdeck and it has worked fine until the new version is come. now it shows missing dependency requires wmctrl and xdotool install from your package manager.  i tried everything i have even make a factory reset but unsuccessful.. I really dont know what to do.   if someone can help me i pay

**Comment by aclist** [comment]
I'll revert this change for now, since ideally it should be possible to run everything out of the box on Steam Deck without installing additional dependencies, but due to changes in the Steam beta client, we'll probably need to enforce this dependency for proper targeting of the client in the future.
