### ISSUE TITLE
DayZ performance degradation on Steam Deck while in-game

### ISSUE THREAD

**Issue by TwinDracos** [aclist/dztui#69]
Recently updated on accident from what was working perfectly to now my games crash every 5-10 minutes. not to sure whats going on and already tried resetting the device and starting from scratch. when the games crash, it just freezes until everything closes out and sometimes that incudes steam its self.

**Comment by aclist** [comment]
Hello, thanks for your message. I understand your concern, but let me clarify:

- DZGUI does not touch or take control of DayZ after it launches. It just asks Steam to open the game.
- DZGUI does not run inside of DayZ.
- DZGUI has no effect on the game or performance itself.
- DZGUI is fully external to the game.
- DZGUI is incapable of crashing a running game because it does not issue any commands while the game is open.

It sounds like there is a different factor in your system that is causing a false positive. This could be something like: 

- A driver or kernel change in your distribution.
- Performance instabilities on the server you are playing on
- Anti-cheat triggering and kicking you off for some reason, perhaps you forgot to set a player name?
- Steam Deck OS instability. Steam Deck is constantly changing versions and introducing regressions

When you said "device," I assume you mean a Steam Deck?

Have you tried switching to the Steam Stable branch? Have you tried using the Stable UI and not the Beta UI?
