### ISSUE TITLE
Ordering fails when server has more than 99 players or less than 10.

### ISSUE THREAD

**Issue by MatheusLasserre** [aclist/dztui#70]
When a server has more than 99 players and i try to order it by number of players, if the server has more than 99, it will be next to the ones with 0 players.

This one most of the time has more than 100 players: ID 16913178

Sometimes server with 4 players get put next to server with 40 players in the ordering, but the guess that i have is that it's being accounted as 40 instead of 4, 30 instead of 3 and so on.

BTW, do you like if i keep spotting minor bugs like this?

Because honestly, none of them bothers me, i just feel like i should tell you

**Comment by aclist** [comment]
> When a server has more than 99 players and i try to order it by number of players, if the server has more than 99, it will be next to the ones with 0 players.

Is this on Server Browser or My Servers?

The GUI being used has a really primitive implementation of number sort, so it only sorts numbers by number of digits, rather than by human readable size. This is why, on the Server Browser, I had to zero-pad the player count as: `005/040`. Since >100 players is 4 digits, we would need to pad everything to four significant digits. This is kind of ugly, but unfortunately there isn't another workaround. I already feel like `001/004` is kind of ugly, but now it's going to be `0001/0004`. Not sure how I feel about this...what do you think?

> Sometimes server with 4 players get put next to server with 40 players in the ordering, but the guess that i have is that it's being accounted as 40 instead of 4, 30 instead of 3 and so on.

This shouldn't be happening, I guess it's on My Servers? My Servers uses the old implementation, but I can add zero-padding there.

> BTW, do you like if i keep spotting minor bugs like this?

Yes, I love it. Keep 'em coming.

**Comment by MatheusLasserre** [comment]
> Is this on Server Browser or My Servers?

It's on my Servers.

If the only way is with zero-padding, i think it's better the way it its now. I think it's prettier.

Also, i think there's too few server with >100 players to add a zero padding that will appear like a extra zero for 99% of the servers, compromising the interface just for them. And since they only bug when the current count is >100, they will appear at the edge of the list, sorting it in a weird way but, well, since it's a edge case with predictable behavior it's ok, isn't it?

Another thing is that sorting by players is useful to check for almost full servers, and it's easier to see it without the zero padding, plus the >100 being at the edge it's kinda o sorting it in a weird way? So i think it's not worth the visual compromise.

About the ones with few people being at the middle, well... since most of the time people will sort looking for the full ones, i don't see it as a problem.  That's at least how i use it.

And i think it's fair to say that i prefer things prettier with few compromises that aren't big deal than fixing them by some visual costs, so maybe i was a little biased, hahahaha

**Comment by MatheusLasserre** [comment]
By the way, i just noticed something: when i get into my servers and the list appears, it's already ordered by the numbers of player. AND without any mistake or zero-padding. I refreshed it a few times and that was always the case. I don't know if it's just a coincidence, so maybe that's an useful info?

If that's right, maybe it's possible to the sorting restore the initial state when toggling for descending, and invert the initial state when toggling for ascending?

I don't know much about Shell Script, so that's just a random impression

**Comment by aclist** [comment]
> Also, i think there's too few server with >100 players to add a zero padding that will appear like a extra zero for 99% of the servers, compromising the interface just for them. And since they only bug when the current count is >100, they will appear at the edge of the list, sorting it in a weird way but, well, since it's a edge case with predictable behavior it's ok, isn't it?

Yes, at least the behavior is well-defined. I'd venture to guess that this limitation is fixed in [yad](https://github.com/v1cont/yad), which is a fork of zenity. zenity is no longer maintained, but we use it because it is available out of the box on Steam Deck, so there's no additional dependency layer there.

> Another thing is that sorting by players is useful to check for almost full servers, and it's easier to see it without the zero padding, plus the >100 being at the edge it's kinda o sorting it in a weird way? So i think it's not worth the visual compromise.

I added the padding to the Server Browser because there are so many results in the list that it's important to be able to sort them, and the results get streamed in and loaded on the fly, so they don't show up in order automatically. I agree that it's less useful on the My Servers page, because a user is unlikely to have more than two dozen servers saved at most (I guess).

> By the way, i just noticed something: when i get into my servers and the list appears, it's already ordered by the numbers of player. AND without any mistake or zero-padding. I refreshed it a few times and that was always the case. I don't know if it's just a coincidence, so maybe that's an useful info? If that's right, maybe it's possible to the sorting restore the initial state when toggling for descending, and invert the initial state when toggling for ascending?

Yes, that's true, but sorting by clicking on columns is a behavior embedded in the zenity GUI. We don't have any control over what happens when a column in the table gets clicked, unfortunately. All we can do is prepare the list and pass it to the GUI when creating the table, but sorting actions are hardcoded internally in the GUI program. This can't be fixed without patching zenity itself, and at that point, we are back to square one with Steam Deck because it won't work out of the box.

Sorting the table works best when alpha-sorting (by server name) or if it's zero padded. Otherwise, there is unfortunately no granular way to tell zenity to prefer one sort algorithm over another on a per-column basis, and it seems to only have a primitive alpha and numerical sort.

My Servers originally existed before the Server Browser, and I thought it was better at the time to list the players as `N/MAX`, but I split it into two columns on the Server Browser for the above reasons.

On balance, I think people using My Servers are more likely going to be searching for a specific server by name rather than sorting heavily by player count. You're kind of an outlier here because your server list is pretty large by most standards.

**Comment by MatheusLasserre** [comment]
I think that's really the better solution. I'm with you on everything. If it was just a bug, was worth a fix. But considering everything that you said, i agree with you will the decisions.

> You're kind of an outlier here because your server list is pretty large by most standards.

Not gonna lie, that was unexpected, hahahahaha. That's maybe because i have like 8 brazillians servers, and that's all we got here. So sometimes they're all full, so i added some American servers.

**Comment by aclist** [comment]
Alright, sounds good. I'm waiting for your next bug ticket. :wink:

**Comment by aclist** [comment]
By the way, what if we presorted the My Servers list by alpha-order so that you can find the server by name faster when loading the list the first time?

**Comment by MatheusLasserre** [comment]
I think that's an awesome idea. This will give a strong sense o stability to the functionality , since without changes on the list, it will always be the same. I like it!

**Comment by aclist** [comment]
OK, the change will be included in 3.3.0, which I think will go live later today.
