### ISSUE TITLE
UX Suggestions

### ISSUE THREAD

**Issue by MatheusLasserre** [aclist/dztui#71]
Hey, aclist! How are you?

Is it possible do put a refresh button on "My Servers"? I usually keep pressing cancel and then entering again to refresh the status of the server. I don't know if this is a common behavior, but i like to do it before entering to see which server is getting full, to check if my ping is stable and so on.

Another thing, is it possible to when clicking the close button, the whole app closes? When you're into some tab and click the close button, it get's back to the main menu and then it's able to close.

Edit:

Oh, i remembered something else. Is it possible that, when scanning for the mods, there's a toggle somewhere to show all mods missing install?

So when can manually add every mod and just wait, instead of waiting for the installation of every single one. 

Or, i don't know, a "Express" instalation mode or something, that if checked, when going to install the app just walk you through every mod to be installed, and the appears a waiting dialog "Press Ok when all mod are downloaded", so after ok it just checks and prepare launch if everything is fine.

Just some ideas that i had!

**Comment by aclist** [comment]
Hello,

> Is it possible do put a refresh button on "My Servers"? I usually keep pressing cancel and then entering again to refresh the status of the server. I don't know if this is a common behavior, but i like to do it before entering to see which server is getting full, to check if my ping is stable and so on.

Off the top of my head, the table mode of zenity only exposes two buttons per menu: Cancel and OK. The `yad` fork of zenity allows an arbitrary number of buttons and interactive widgets onscreen. In any event, due to the design of zenity, "refreshing" the page would essentially involve destroying the window and spawning a new one. It might be possible to hack this by making the table essentially read continuously from a FIFO that gets updated when the user triggers the "refresh" command, but this might be fraught with problems. I've seen people describe the DZGUI interface as primitive, but the application is not intentionally obtuse by design. It's just that, in deciding to also target Steam Deck, it's really tied our hands with what we can do on the UI front if we expect it to run out of the box.

My opinion on this is kind of divided right now, because DZTUI was originally a desktop-only app, but the overwhelming demand from people wanting to play DayZ on Steam Deck led to the graphical widget we now know was DZGUI. On the upside, it's made things a lot easier and more interactive, such as when scrolling through lots of servers. On the other hand, Steam Deck has brought an almost impossible level of complications and non-desktop users usually have a hard time explaining or reproducing the issues they encounter, due to the "kiosk mode" design of Steam Deck.

Anyway, I won't say it is impossible, but I would have to stretch the limits of zenity to find a solution. Maybe at some point we should go back to a "DZGUI desktop version" (more freely extensible) and "DZGUI Steam Deck version" (feature-locked) to avoid this insanity.

> Another thing, is it possible to when clicking the close button, the whole app closes? When you're into some tab and click the close button, it get's back to the main menu and then it's able to close.

This seems kind of like an anti-pattern: what if you actually want to go back a few menus? I guess you are talking about a third cancel mode that is like "quit to desktop." Again, I'd have to see if we can somehow force a third button into menus.

> Oh, i remembered something else. Is it possible that, when scanning for the mods, there's a toggle somewhere to show all mods missing install?

If I understand you correctly, there is an "auto-mod installation" mode hidden in the advanced options menu. This attempts to stage all mods for download in bulk. It should work reliably on the Steam Stable client, but it needs refactoring due to changes in the Steam Beta client. Auto-mod installation is a highly experimental feature (although it's the one I mainly use myself) and development of it is mostly going on under the Testing branch, which you have to toggle on in the advanced options menu as well. This mode is still available in the stable branch of DZGUI, but the Testing branch will have more recent updates as far as that mode is concerned. However, be aware that the testing branch is just that: a sandbox, so it has frequent updates and may be prone to unexplained breakage.

As of this writing, I don't have any problems using auto-mod installation on the testing branch + the latest version of DZGUI + Steam Stable client. I don't advertise this feature much because it's not mature.  You'll need `wmctrl` and `xdotool` as dependencies to use it.

I realize that manual mode can be slow and boring, but the reason it waits for the mods to download is because there's a non-zero chance the subscription will fail, in which case the user should re-subscribe, and getting them back to the right mod window is going to be hard if they just blow past it all. On the other hand, the auto-mod installation mode just throws caution to the wind and bulk requests every mod.

**Comment by MatheusLasserre** [comment]
Sorry for the late response. I think the way it is is already great! Even without the suggestions - suggestions which some are not even good. I've been using it for a long time and i'm really satisfied the way it is.
