### ISSUE TITLE
DayZ not found

### ISSUE THREAD

**Issue by JonahGroendal** [aclist/dztui#72]
Keep getting error message "DayZ not found or not installed at the chosen path."

I followed the install manual and pointed the program to ~/.var/app/com.valvesoftware.Steam/.local/share/Steam yet it still does not work

The game is installed and steam is open

**Comment by aclist** [comment]
Thanks for your message.

1. Do you have multiple drives?
2. Check `/tmp/dzdebug.log` and post the contents here.
3. Post the contents of `$HOME/var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/libraryfolders.vdf`

**Comment by mtwx1** [comment]
I have same issue. There will be many tries inside dzdebug.log because I have tried many different ways to make it work, but in general it failed all the time.
[dzdebug.log](https://github.com/aclist/dztui/files/11585047/dzdebug.log)
[libraryfolders.txt](https://github.com/aclist/dztui/files/11585052/libraryfolders.txt)

**Comment by JonahGroendal** [comment]
For some reason I don't have a /tmp/dzdebug.log file.

[libraryfolders.vdf.txt](https://github.com/aclist/dztui/files/11585167/libraryfolders.vdf.txt)

I'm on Ubuntu 22.04

**Comment by JonahGroendal** [comment]
I ran the script with `sudo` just now and while it didn't magically fix anything it did generate the log file:

[dzdebug.log](https://github.com/aclist/dztui/files/11585192/dzdebug.log)

**Comment by aclist** [comment]
@JonahGroendal 

Many thanks for the detailed information, very helpful. It appears that Steam's internal files are reporting that DayZ (appid 221100) is not a part of the user's library within the files installed at `$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam`.

Follow-up questions:

1. Is this Steam Stable client or Steam Beta client?
2. Do you have multiple drives (Steam Settings > Downloads > Steam Library Folders)? On inspection of the file, it does not report any additional drives.
3. Have you tried restarting Steam since installing DayZ to regenerate the library metadata?

DZGUI reads from the files Steam reports to determine where DayZ is literally installed by Steam. It is not clear why DayZ is absent from this master list. According to this list, you have 18 games installed. Is that correct?

4. Additional data point from me: I have only seen this bug once from another user on Flatpak Steam. I will investigate whether Flatpak Steam stores appid info elsewhere than the canonical location.

@mtwx1

Same questions to you.

While I research point 4 above, as a control test, I suggest both of you to try Steam Stable branch and/or native Steam (not Flatpak) if either of those apply to  you. If either of those is the cause, I'll find a way of properly targeting this metadata.

I appreciate that both of you reported this issue, as that makes three total reports of this bug, so we have enough to identify it as more than just a passing anomaly.

**Comment by aclist** [comment]
> I ran the script with sudo just now and while it didn't magically fix anything it did generate the log file:

It's not necessary to use elevated permissions to run DZGUI. Looks like the sticky bit was set on /tmp and the user probably didn't have ownership there. I'll look into moving logs into a more standardized location accessible by the user.

**Comment by aclist** [comment]
As a fifth data point, have either of you at some point manually moved the DayZ installation out of where you originally installed it or used Steam's internal feature to "move" a game from one drive to another? The dialog looks like this: https://www.howtogeek.com/wp-content/uploads/2017/01/click-move.png

**Comment by JonahGroendal** [comment]
I'll try restarting steam and running the script again. I have a feeling that might work.

As for user access to /tmp, I am able to navigate into the folder and save files to that location as a regular user, so it doesn't seem like a permissions issue? Not really sure what's going on there.

**Comment by aclist** [comment]
> I'll try restarting steam and running the script again. I have a feeling that might work.

Please, if possible, answer all of the questions above so I can definitively rule out what this bug is not being caused by. Identifying and isolating the scope is half the battle. Solving it is the easy part.

**Comment by JonahGroendal** [comment]
Yep it worked. Just had to restart steam then it worked without me even having to select the steam library folder manually.

I probably should have thought to restart steam but it might be worth putting this instruction into the manual. Or, better yet, in a dialog if the script fails to find DayZ. 

Much thanks for the help and for creating/maintaining this tool.

**Comment by mtwx1** [comment]
> 

Hi,

1. I am not sure, I use default installed Nobara Steam client. I believe it is stable version, but I could check, but I dont know how or where.
2.  No I have single SSD in my system. Today I have reinstalled Nobara, copied steamapps folder backup from external drive. On Steam installed DayZ again. It checked the files and game appeared as installed.
3. Yes, I have restarted Steam also PC. Tried again, same.

BTW 

I dont have 5 games installed. I only have DayZ and New World on my system as of right now.

**Comment by mtwx1** [comment]
> > 
> 
> Hi,
> 
>     1. I am not sure, I use default installed Nobara Steam client. I believe it is stable version, but I could check, but I dont know how or where.
> 
>     2. No I have single SSD in my system. Today I have reinstalled Nobara, copied steamapps folder backup from external drive. On Steam installed DayZ again. It checked the files and game appeared as installed.
> 
>     3. Yes, I have restarted Steam also PC. Tried again, same.
> 
> 
> BTW
> 
> I dont have 5 games installed. I only have DayZ and New World on my system as of right now.

Forgot to add that external is disconnected

**Comment by mtwx1** [comment]
I did first time setup again and it found DayZ automatically. 

After you said that if I have 5 games installed, I deleted Libraryfolder file, restarted steam. It created new file. Then  I ran script again and voula- it works!

**Comment by aclist** [comment]
@JonahGroendal 

Good to hear. It seems like the root cause here may be a previous instance of Steam running and never having been closed down, preventing the metadata from refreshing with games that were added/moved/installed in the interim. I am not 100% sure if your case is identical to mtwx1's below, but they are shades of the same thing. We should probably warn the user to make sure Steam has been restarted at least once before running DZGUI, preferably stopping them from even getting to this point of being in a loop of menus, and to be cautious when forcibly copying over backed up Steam games onto a new drive. (In theory, Steam provides some functionality for doing this, but not sure if it is foolproof.)

@mtwx1 

OK, great, forcibly removing the file works, too. The file should always regenerate itself and be replaced with a more up to date version once you launch Steam. However, if you have moved around files from backup, this file is likely to get out of synch and not list the proper place games were installed, since Steam "loses track" of where the paths are if they get manually moved from backup. I should probably make a note to reproduce this behavior and report it to Valve.

**Comment by JonahGroendal** [comment]
@aclist Oh right, I forgot to answer your question about moving games or having multiple drives/Library folders. I haven't moved any games and I only have the one library folder.
