### ISSUE TITLE
A Discord Server

### ISSUE THREAD

**Issue by jordan4ibanez** [aclist/dztui#75]
I think it would be very nice if we had a Discord server so we could talk about improvements and features in real time.

**Comment by aclist** [comment]
Due to lag time, please submit comments and PRs in the form of formal tickets on this bug tracker so that they can reviewed asynchronously, publicly indexed, and openly accessed by search engines. Development should take place in the open. There is also a discussion forum on this repository located here: https://github.com/aclist/dztui/discussions
