### ISSUE TITLE
openSUSE Tumbleweed, dztui gets stuck in a loop

### ISSUE THREAD

**Issue by jordan4ibanez** [aclist/dztui#78]
When you go to the server browser, it will automatically load the first entry then go back to the main portion.

When you manually add a server and try to browse your servers, it gets stuck in a loop, closing and opening the window infinitely.

**Comment by aclist** [comment]
Thanks for the report. There are some issues with certain distros due to bugs in an upstream package being carried by some distros.

Could you please report the following:

- DZGUI version
- OS version and kernel version
- Zenity version (`zenity --version`)
- List of servers and ID of server you are trying to add
- Contents of debug log (Advanced options > Generate debug log)

**Comment by jordan4ibanez** [comment]
- DZGUI version =
3.3.7/3.3.10
- OS version and kernel version =
openSUSE Tumbleweed 20230814, 6.4.9-1-default
- Zenity version (zenity --version) =
3.99.0
- List of servers and ID of server you are trying to add
    Contents of debug log (Advanced options > Generate debug log)
Literally any of them - Also the log will not generate at all

**Comment by aclist** [comment]
The missing log generation has been fixed in `3.3.11`, this was a bug. It should generate a `DZGUI.log` file from the root directory now. It also generates a `DZGUI_DEBUG.log` file when running and exiting the application. Please attach both.

Regarding menus despawning, due to the newness of the zenity version, most likely it relates to https://gitlab.gnome.org/GNOME/zenity/-/issues/61#note_1810359, wihch is also being tracked at #74, but may be a separate issue.

Is the server browser the only menu that behaves this way?

**Comment by jordan4ibanez** [comment]
Ahem, new problem, uhh, even with the older, newer, and mainline version, it just dies when I push server browser.
It just goes away but the process is still running.


    DZGUI version =
(any)
    OS version and kernel version =
openSUSE Tumbleweed 20230819
    Zenity version (zenity --version) =
3.99.0
    List of servers and ID of server you are trying to add =
literally anything explained above
    Contents of debug log (Advanced options > Generate debug log) =
This is as far as it got
```
u@r-very-nosey:~> /home/mrmagoo/.local/share/dzgui/dzgui.sh
# Initial setup
[DZGUI] Setting architecture to 'desktop'
[DZGUI] Checking system map count
# Checking news
100
[DZGUI] Toggled debug flag to '1'
```

**Comment by jordan4ibanez** [comment]
I would like to also add another note: now it's just dying when I try to add a server by IP or add server by id

**Comment by aclist** [comment]
>This is as far as it got

This is not the debug log generated from within DZGUI, it is the runtime debug log. The debug log inside of DZGUI is now called "Output system info".

> I would like to also add another note: now it's just dying when I try to add a server by IP or add server by id

The codebase affecting this has not changed since any of your messages above. Have you followed the instructions at the GNOME mailing list link above and tried downgrading zenity to a different version?

Also, have you tried reinstalling DZGUI?

Finally, you must define what "dying" refers to in this context.

**Comment by jordan4ibanez** [comment]
I have a good update: I gave up on OpenSUSE, works on Linux Mint
