### ISSUE TITLE
[BUG] Unresponsive keyboard on Steam Deck desktop mode

### ISSUE THREAD

**Issue by TheKoteee** [aclist/dztui#87]
Please tell me how to return the ability to launch dzgui from game mode on SteamDeck, because I'm having difficulties with the control in desktop mode, I can't call the keyboard and I can't see the controller animations

**Comment by aclist** [comment]
Could you tell me how you are launching DZGUI when in Desktop Mode? Through Steam or through the desktop shortcut?

**Comment by aclist** [comment]
Alright, I am investigating on a Steam Deck test bench. Game Mode support was dropped because of a Steam bug preventing keyboard input that was affecting a lot of users. Can you clarify the below?

- When you say that you can't call the keyboard, are you talking about in DZGUI or after launching DayZ?
- When you say "controller animations," are you talking about Steam Deck radial menus (pictured at left in [this screenshot](https://steamcdn-a.akamaihd.net/steamcommunity/public/images/steamworks_docs/english/slime_rancher_0.png))?

**Comment by TheKoteee** [comment]
- I can't call the keyboard after launching DayZ
- yes I talking about a radial menu looks like on screenshot.

**Comment by TheKoteee** [comment]
Before I updating DZGUI,  I'm launching DZGUI in gaming mode and all in DayZ working okay
Sorry for my English it was Google translate 😓

**Comment by aclist** [comment]
> Sorry for my English it was Google translate 😓

No problem.

> Before I updating DZGUI, I'm launching DZGUI in gaming mode and all in DayZ working okay

Unfortunately, there was a problem where typing any keyboard entry in DZGUI (e.g. typing server IPs) was not working in Gaming Mode. This is due to a Steam Deck bug that I reported to Valve last year.

I'm investigating the problem and will see if we can find a solution that satisfies both modes. On my test bench, I was able to get keyboard working on Desktop Mode when using the shortcut. I will keep investigating, please stand by. Thank you.

**Comment by aclist** [comment]
Sure, see below (line 1746):

Before:

```
check_architecture(){
	logger INFO "${FUNCNAME[0]}"
	cpu=$(cat /proc/cpuinfo | grep "AMD Custom APU 0405")
	if [[ -n "$cpu" ]]; then
		is_steam_deck=1
		logger INFO "Setting architecture to 'Steam Deck'"
        [[ $is_steam_deck -eq 1 ]] && test_display_mode
        if [[ $gamemode -eq 1 ]]; then
            popup 1400 &&
            exit 1
        fi
	else
		is_steam_deck=0
		logger INFO "Setting architecture to 'desktop'"
	fi
}
```

After:

```
check_architecture(){
	logger INFO "${FUNCNAME[0]}"
	cpu=$(cat /proc/cpuinfo | grep "AMD Custom APU 0405")
	if [[ -n "$cpu" ]]; then
		is_steam_deck=1
		logger INFO "Setting architecture to 'Steam Deck'"
        [[ $is_steam_deck -eq 1 ]] && test_display_mode
	else
		is_steam_deck=0
		logger INFO "Setting architecture to 'desktop'"
	fi
}
```

**Comment by TheKoteee** [comment]
> Звичайно, див. нижче (рядки 1753-1756):
> 
> ```diff
> check_architecture(){
> 	logger INFO "${FUNCNAME[0]}"
> 	cpu=$(cat /proc/cpuinfo | grep "AMD Custom APU 0405")
> 	if [[ -n "$cpu" ]]; then
> 		is_steam_deck=1
> 		logger INFO "Setting architecture to 'Steam Deck'"
>         [[ $is_steam_deck -eq 1 ]] && test_display_mode
> -        if [[ $gamemode -eq 1 ]]; then
> -            popup 1400 &&
> -            exit 1
> -        fi
> 	else
> 		is_steam_deck=0
> 		logger INFO "Setting architecture to 'desktop'"
> 	fi
> }
> ```

in the game mode, the message that you need to start the DZGUI in the desktop mode no longer appears, but the program still closes smoothly

**Comment by aclist** [comment]
Attach your dzgui.sh here and I will check for anomalies. Also, make sure you are modifying the file `$HOME/.local/share/dzgui/dzgui.sh`.

**Comment by aclist** [comment]
The file is clean. I am not able to reproduce this behavior. After removing those lines from `dzgui.sh` and launching it in Game Mode, it passes all of the initial setup checks and loads--no exit.

Make sure you have added the right file as a non-Steam game as described [here](https://aclist.github.io/dzgui/dzgui.html#_steam_integration_artwork). If necessary, reinstall DZGUI and remove those lines again, save the file, then switch to Game Mode.

As for the underlying issue, I spoke with a DZGUI beta tester, and it is deeper than I expected. Basic summary follows:

A) On Steam Deck game mode, DZGUI keyboard input works for basic navigation, but not for virtual text entry (e.g. filling in ID or IP). However, inside of DayZ, keyboard input works when using Game Mode -> DZGUI -> DayZ. This is part of the SteamOS bug reported to Valve previously.
B) On Steam deck desktop mode, DZGUI keyboard input works for basic navigation AND virtual text entry. However, inside of DayZ, keyboard input does NOT work when using Desktop Mode -> DZGUI -> DayZ, unless a secondary keyboard (USB, Bluetooth, etc.) is connected to the Steam Deck.

Based on the above, I am going to make two fixes:

- Drop the warning that blocks DZGUI from launching on Game Mode
- If the device is Steam Deck and using Game Mode, implement different input menus so that keyboard entry works

Expected result should be:

- User can type into forms in DZGUI
- User can use keyboard inside of DayZ itself

Users would then be encouraged to use DZGUI through Game Mode until the root cause of item B) above is found.

Will need a few days to issue this fix.

**Comment by TheKoteee** [comment]
Thank you for everything and sorry if i bother you.

**Comment by aclist** [comment]
I will notify you when the fix is ready. Sorry for the inconvenience and hope you can enjoy DayZ during that time with some minor flaws.

**Comment by TheKoteee** [comment]
I deleted the folder( Home\.config\dztui) and configured everything again. After that all working good in gaming mod 🥳

**Comment by aclist** [comment]
I have made some changes that will allow for submitting text input into entry fields when using Game Mode and will restore the Game Mode functionality in the next release. I have also learned that when using Steam Deck, you can long-press the three dots button (...) on the right of the device to unlock the mouse and toggle mouse input. These changes will go into the Stable branch on Friday of this week.

**Comment by aclist** [comment]
Game Mode support has been restored to the Stable version of DZGUI, 4.1.0.
